### ISSUE TITLE
serve-expired-ttl & Redis

### ISSUE THREAD

**Issue by mibere** [NLnetLabs/unbound#107]
Let's assume unbound.conf contains

```
server:
  prefetch: yes
  serve-expired: yes
  serve-expired-ttl: 7200
  ...

cachedb:
  backend: "redis"
  redis-server-host: 127.0.0.1
  redis-server-port: 6379
```

It doesn't contain 'serve-expired-ttl-reset'.

A client visits a domain (it's TTL is 3600) for the first time: Unbound can't find an answer to this query in its built-in in-memory cache and also not in the backend (Redis). So Unbound has to resolve the query as usual (iterative DNS resolution) and stores the answer in it's cache and in Redis.

5 hours later...the client visits and requests the above domain again.
What happens now? Especially in regard to the configured 'serve-expired-ttl' in combination with Redis.
