### ISSUE TITLE
Unbound Serve expired; cache hit rate reducing with time

### ISSUE THREAD

**Issue by sirizake** [NLnetLabs/unbound#1115]
Hi 
I have installed unbound version: 1.20.0 on a FreeBSD 14 server. This was working fine until the server lost internet connectivity to the upstream internet provider. Prior to this the average cache hit rate on the server was 99.0% with only 1% recursive replies.
Part of my unbound.conf file is shown below

```yaml
server:
    prefetch: yes
    serve-expired: yes
# serve-expired-ttl: 0
 # serve-expired-ttl-reset: no
```

After loss of internet average cache hit rate has reduced to 14% whiles recursive queries is showing 86% (still internet is not restored)
My expectation is 
Caching server should continue to serve expired and keep the cache hit rate high because the serve-expired-ttl is default 
(meaning it should continue serving cached content until upstream is restored).
My observation is the opposite.  Is there anything I am missing? How can i ensure that the caching server will continue serving cache data several days after upstream
internet is lost
Regards
Isaac
