### ISSUE TITLE
[-273754571] libunbound[19:0] error: gettimeofday: Value too large for defined data type

### ISSUE THREAD

**Issue by aikooo7** [NLnetLabs/unbound#1120]
**Describe the bug**

When using the docker compose image arm64, I get the following error:

```
[-273754571] libunbound[19:0] error: gettimeofday: Value too large for defined data type
```

**To reproduce**
1. Run the following docker compose:

```
services:
  unbound:
    image: mvance/unbound-rpi:latest
    container_name: unbound
    restart: unless-stopped
    networks:
      - proxy-network
```
2. Check logs

**Expected behavior**

Run normally

**System:**
 - Unbound version: 
 ```
 Version 1.19.2

Configure line: --disable-dependency-tracking --prefix=/opt/unbound --with-pthreads --with-username=_unbound --with-ssl=/opt/openssl --with-libevent --with-libnghttp2 --enable-tfo-server --enable-tfo-client --enable-event-api
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 3.2.1 30 Jan 2024
Linked modules: dns64 respip validator iterator
TCP Fastopen feature available

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```
 - OS: 

``` 
Linux localhost 4.19.315-perf+ #4 SMP PREEMPT Sun Jul 21 23:42:00 WEST 2024 aarch64 Android
```

```
Docker version v1:24.0.6-ce, build
```

**Additional information**
Add any other information that you may have gathered about the issue here.

This might be a issue related to android kernel itself...
