### ISSUE TITLE
many problems with unbound resolving dns names

### ISSUE THREAD

**Issue by myssv** [NLnetLabs/unbound#1133]
**Describe the bug**
after installing unbound and connecting it with my adguard I have problems with many websites, which are not working anymore. For example support.google.com. The name is not resolved.

**To reproduce**
When I only habe unbound as the upstream dns server in adguard teh domain is not resolved. Adding an other DNS server to adguard everything is fine.

**System:**
 - Unbound version: 1.17.1
 - OS: Debiar 12
 - `unbound -V` output:
```
root@AdGuard:~# unbound -V
Version 1.17.1

Configure line: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-pythonmodule --with-pyunbound --enable-subnet --enable-dnstap --enable-systemd --with-libnghttp2 --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --disable-rpath --with-pidfile=/run/unbound.pid --with-libevent --enable-tfo-client --with-rootkey-file=/usr/share/dns/root.key --enable-tfo-server
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 3.0.13 30 Jan 2024
Linked modules: dns64 python subnetcache respip validator iterator
TCP Fastopen feature available

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

Examples with only unbound:
```
PS C:\Users\Volke> ping support.google.com
Ping-Anforderung konnte Host "support.google.com" nicht finden. Überprüfen Sie den Namen, und versuchen Sie es erneut.

PS C:\Users\Volke> ping google.com

Ping wird ausgeführt für google.com [142.251.209.142] mit 32 Bytes Daten:
Antwort von 142.251.209.142: Bytes=32 Zeit=3ms TTL=118
Antwort von 142.251.209.142: Bytes=32 Zeit=3ms TTL=118
Antwort von 142.251.209.142: Bytes=32 Zeit=3ms TTL=118
Antwort von 142.251.209.142: Bytes=32 Zeit=4ms TTL=118

Ping-Statistik für 142.251.209.142:
    Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 3ms, Maximum = 4ms, Mittelwert = 3ms
```

**Comment by wcawijngaards** [comment]
With the command 'dig' the server can be inspected to see what answers it gives. With dig '@' and the IP address and the query to look at. For unbound, the verbosity can be increased to say, level 4 or 5. This prints more details, and that may provide useful information if you look at it; in particular it prints the 'dig' like output from the upstream lookups and what it then does with that. The `log-servfail: yes` option is useful in that it prints single-line error messages that talk about failed lookups.

**Comment by myssv** [comment]
This is what I got:

```
root@AdGuard:~# dig @192.168.115.210 support.google.com

; <<>> DiG 9.18.28-1~deb12u2-Debian <<>> @192.168.115.210 support.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32446
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;support.google.com.		IN	A

;; Query time: 47 msec
;; SERVER: 192.168.115.210#53(192.168.115.210) (UDP)
;; WHEN: Fri Aug 30 10:16:10 CEST 2024
;; MSG SIZE  rcvd: 47
```

**Comment by wcawijngaards** [comment]
Surprising result, it prints no error, but also no data. It must have got a response somehow with zero data for this item. Is there items in the unbound configuration that deal with the name, `support.google.com` ? Like local-zone or forward or stub items, those would redirect the answer to a different value.

**Comment by wcawijngaards** [comment]
The config items, `log-local-actions: yes` and `log-queries: yes` and `log-replies: yes` can be useful here. With log local actions, it is visible that a local data or local zone action is performed, and the query and reply are then logged. Also the higher verbosity is then useful, so that the unbound logs contain relevant data about the question.

**Comment by myssv** [comment]
I have 4 conf-files here:

adguardhome.comf
```
server:
    # If no logfile is specified, syslog is used
    # logfile: "/var/log/unbound/unbound.log"
    verbosity: 0

    interface: 127.0.0.1
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: yes

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: no

    # Use this only when you downloaded the list of primary root servers!
    # If you use the default dns-root-data package, unbound will find it automatically
    root-hints: "/var/lib/unbound/root.hints"

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    harden-dnssec-stripped: yes

    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size.
    # IP fragmentation is unreliable on the Interftreternet today, and can cause
    # transmission failures when large DNS messages are sent via UDP. Even
    # when fragmentation does work, it may not be secure; it is theoretically
    # possible to spoof parts of a fragmented DNS message, without easy
    # detection at the receiving end. Recently, there was an excellent study
    # >>> Defragmenting DNS - Determining the optimal maximum UDP response size for DNS <<<
    # by Axel Koolhaas, and Tjeerd Slokker (https://indico.dns-oarc.net/event/36/contributions/776/)
    # in collaboration with NLnet Labs explored DNS using real world data from the
    # the RIPE Atlas probes and the researchers suggested different values for
    # IPv4 and IPv6 and in different scenarios. They advise that servers should
    # be configured to limit DNS messages sent over UDP to a size that will not
    # trigger fragmentation on typical network links. DNS servers can switch
    # from UDP to TCP when a DNS response is too big to fit in this limited
    # buffer size. This value has also been suggested in DNS Flag Day 2020.
    edns-buffer-size: 1232

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    module-config: "validator iterator"
    prefetch: yes

    # One thread should be sufficient, can be increased on beefy machines. In reality for most users running on small networks or on a single machine, it should be unnecessary to seek performance enhancement by>
    num-threads: 1

    # Ensure kernel buffer is large enough to not lose messages in traffic spikes
    so-rcvbuf: 1m

    # Ensure privacy of local IP ranges
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.0.0.0/8
    private-address: 10.0.0.0/8

    # eigene Anpassungen
    qname-minimisation: yes

```


hyperlocal.conf
```
# =========================================================
# Auth Zone for the Internet root zone "."
# See RFC 8806 - Running a Root Server Local to a Resolver
# https://www.rfc-editor.org/rfc/rfc8806.html
# =========================================================
auth-zone:
    name: "."
    master: "b.root-servers.net"
    master: "c.root-servers.net"
    master: "d.root-servers.net"
    master: "f.root-servers.net"
    master: "g.root-servers.net"
    master: "k.root-servers.net"
    url: https://www.internic.net/domain/root.zone
    fallback-enabled: yes
    for-downstream: no
    for-upstream: yes
    zonefile: "/etc/unbound/root.zone"
```

remote-control.conf
```
remote-control:
  control-enable: yes
  # by default the control interface is is 127.0.0.1 and ::1 and port 8953
  # it is possible to use a unix socket too
  control-interface: /run/unbound.ctl
```

root-auto-trust-abchor-file.conf
```
server:
    # The following line will configure unbound to perform cryptographic
    # DNSSEC validation using the root trust anchor.
    auto-trust-anchor-file: "/var/lib/unbound/root.key"

```
