### ISSUE TITLE
unbound-anchor fails, claiming file does not exist

### ISSUE THREAD

**Issue by owenpmckenna** [NLnetLabs/unbound#1136]
Hello! I'm trying to use unbound dns in docker on my windows pc to secure my traffic (using DNSSEC, as I understand it).

My dockerfile looks like: 
```
FROM ubuntu:22.04
RUN apt update
RUN apt install unbound -y
COPY unbound-new.conf /etc/unbound/
RUN mkdir /usr/local/etc/unbound/
RUN unbound-anchor -vvv -a /usr/local/etc/unbound/root.key -c /etc/unbound/unbound-new.conf
ENTRYPOINT [ "unbound", "-vvv", "-dd", "-c", "/etc/unbound/unbound-new.conf" ]
```
and unbound-new.conf looks like
```
server:
    do-not-query-localhost: no
    trust-anchor-file: '/usr/local/etc/unbound/root.key'
    qname-minimisation: yes
    interface: 127.0.0.1
    access-control: 127.0.0.0/8 allow
    username: 'root'
    chroot: ''
```
I seems like this should work. `unbound-anchor`'s man page claims in regards to the key file `If the file does not exist, or is empty, a builtin root key is written to it.`
When I run the dockerfile build it fails on `RUN unbound-anchor ...` I get the output:
```
/usr/local/etc/unbound/root.key does not exist
success: the anchor is ok 
```
I thought unbound-anchor was supposed to create the file? If anyone has any advice it would be great. It's entirely possible I just missed something obvious. Thank you!
