### ISSUE TITLE
use /etc/resolv.conf to find upstream, and also respect search config

### ISSUE THREAD

**Issue by jjb** [NLnetLabs/unbound#1139]
thanks for a great project!

i have a /etc/resolv.conf like this

```
search my.service.local my.cool.microservices.domain
nameserver 10.0.1.1
options ndots:5
```

with this unbound config:

```yaml
server:
  interface: 127.0.0.1
  pidfile: "/etc/unbound/unbound.pid"
```

queries to unbound for internet domains (e.g. `google.com`) work, but queries to unbound for local domains that require search (e.g. `postgres` → `postgres.my.service.local`) do not work.

with this unbound config:

```yaml
server:
  interface: 127.0.0.1
  pidfile: "/etc/unbound/unbound.pid"

forward-zone:
  name: "."
  forward-addr: 10.0.1.1
```

all domains work, internet and local search.

is there a way to configure unbound to respect the local search config without needing to add the explicit forward-zone block?

Thanks!
