### ISSUE TITLE
unbound failed to start with redis-server-path - ubuntu 24.04

### ISSUE THREAD

**Issue by arasserdaroglu** [NLnetLabs/unbound#1212]
Everything works with TCP, however unbound failed with unix socket.

It says: error: failed to connect to redis server: Permission denied

unbound user is defined in redis group.

unbound version: Version 1.19.2

Error:

```
Jan 09 14:22:06 ubuntu-server systemd[1]: Starting unbound.service - Unbound DNS server...
Jan 09 14:22:06 ubuntu-server (unbound)[2508]: unbound.service: Referenced but unset environment variable evaluates to an empty string: DAEMON_OPTS
Jan 09 14:22:06 ubuntu-server unbound[2508]: [1736432526] unbound[2508:0] warning: so-rcvbuf 4194304 was not granted. Got 425984. To fix: start with root permissions(linux) or sysctl bigger net.core.rmem_max(linux) or kern.ipc.maxsockbuf(bsd) values.
Jan 09 14:22:06 ubuntu-server unbound[2508]: [1736432526] unbound[2508:0] warning: so-sndbuf 4194304 was not granted. Got 425984. To fix: start with root permissions(linux) or sysctl bigger net.core.wmem_max(linux) or kern.ipc.maxsockbuf(bsd) values.
Jan 09 14:22:06 ubuntu-server unbound[2508]: [1736432526] unbound[2508:0] warning: so-rcvbuf 4194304 was not granted. Got 425984. To fix: start with root permissions(linux) or sysctl bigger net.core.rmem_max(linux) or kern.ipc.maxsockbuf(bsd) values.
Jan 09 14:22:06 ubuntu-server unbound[2508]: [1736432526] unbound[2508:0] warning: so-sndbuf 4194304 was not granted. Got 425984. To fix: start with root permissions(linux) or sysctl bigger net.core.wmem_max(linux) or kern.ipc.maxsockbuf(bsd) values.
Jan 09 14:22:06 ubuntu-server unbound[2508]: [2508:0] error: failed to connect to redis server: Permission denied
Jan 09 14:22:06 ubuntu-server unbound[2508]: [2508:0] error: redis_init: failed to init redis
Jan 09 14:22:06 ubuntu-server unbound[2508]: [2508:0] error: cachedb: could not init redis backend
Jan 09 14:22:06 ubuntu-server unbound[2508]: [2508:0] error: module init for module cachedb failed
Jan 09 14:22:06 ubuntu-server unbound[2508]: [2508:0] fatal error: failed to setup modules
Jan 09 14:22:06 ubuntu-server systemd[1]: unbound.service: Main process exited, code=exited, status=1/FAILURE
Jan 09 14:22:06 ubuntu-server systemd[1]: unbound.service: Failed with result 'exit-code'.
Jan 09 14:22:06 ubuntu-server systemd[1]: Failed to start unbound.service - Unbound DNS server.
Jan 09 14:22:06 ubuntu-server systemd[1]: unbound.service: Scheduled restart job, restart counter is at 5.
Jan 09 14:22:06 ubuntu-server systemd[1]: unbound.service: Start request repeated too quickly.
Jan 09 14:22:06 ubuntu-server systemd[1]: unbound.service: Failed with result 'exit-code'.
Jan 09 14:22:06 ubuntu-server systemd[1]: Failed to start unbound.service - Unbound DNS server.
``` 

Unbound.conf

```
# Unbound configuration file for Debian.
#
# See the unbound.conf(5) man page.

# Blocklist
#include: "/opt/unbound/blocklists/unbound.block.conf"

# Configure unbound as recursive DNS resolver
server:
        # |Interface & port|
        interface: 192.168.3.103
        port: 53
        # Allows to bind to interface IP before network is online at boot or network is
        # down. Other solution is use 'interface: 0.0.0.0' to listen on all interfaces.
        ip-freebind: yes

        # |Protocols|
        do-ip4: yes
        do-ip6: yes
        do-udp: yes
        do-tcp: yes
        # Set this to yes to prefer ipv6 upstream servers over ipv4
        prefer-ip6: no

        # |Root|
        # Configures unbound to perform DNSSEC validation using root trust anchor.
        # Unbound user must have write permission to file & dir
        #auto-trust-anchor-file: "/var/lib/unbound/root.key"
        # DNS root servers file. Updated monthly via systemd timer
        root-hints: "/var/lib/unbound/root.hints"

        # |Process|
        # Do not daemonize, to allow proper systemd service control and status
        do-daemonize: no
        # Set num-threads equal to num of CPU cores. Use 1 to disable threading
        num-threads: 2
        # Faster UDP with multithreading
        so-reuseport: yes

        # |Buffers|
        # EDNS reassembly buffer to advertise to UDP peers (the actual buffer
        # is set with msg-buffer-size)
        edns-buffer-size: 1232
        # Increase incoming and outgoing query buffer size to cover traffic peaks
        so-rcvbuf: 4m
        so-sndbuf: 4m

        # |Cache|
        # Slabs reduce lock contention by threads. Set to power of 2, close to num-threads
        msg-cache-slabs: 4
        rrset-cache-slabs: 4
        infra-cache-slabs: 4
        key-cache-slabs: 4
        # rrset-cache-size should be twice of msg-cache-size
        msg-cache-size: 64m
        rrset-cache-size: 128m
        # Time to live minimum for messages in cache. More than an hour could easily
        # give trouble due to stale data. Default is 0
        cache-min-ttl: 0
        cache-max-ttl: 86400
        # Number of bytes size of the aggressive negative cache
        neg-cache-size: 4m
        # Perform prefetching of almost expired message cache entrie
        prefetch: yes
        # Fetch the DNSKEYs earlier in the validation process, when a DS record is
        # encountered. This lowers the latency of requests at the expense of little
        # more CPU usage.
        prefetch-key: yes
        # Have unbound attempt to serve old responses from cache with a TTL of 0 in
        # the response without waiting for the actual resolution to finish. The
        # actual resolution answer ends up in the cache later on.
        serve-expired: yes
        # TTL value to use when replying with expired data. If serve-expired-client-timeout
        # is used then recommended to use 30. Default is 30
        # Added for cachedb warning at unbound start. Unbound sets it to 0 for records
        # originating from cachedb
        serve-expired-reply-ttl: 0

        # |Hardening|
        # Trust glue only if it is within the servers authority
        harden-glue: yes
        # Ignore very large queries.
        harden-large-queries: yes
        # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes bogus
        # To disable DNSSEC, set harden-dnssec stripped: no
        harden-dnssec-stripped: yes
        # Harden against algorithm downgrade when multiple algorithms are advertised in the DS record
        harden-algo-downgrade: yes
        # Ignore very small EDNS buffer sizes from queries.
        harden-short-bufsize: yes

        # |Logging|
        # Verbosity: Default is 1
        # 0 No verbosity, only errors
        # 1 Operational information
        # 2 Detailed operational information
        # 3 Query level information, output per query
        # 4 Algorithm level information
        # 5 Client identification for cache misses
        verbosity: 0
        # Prints one line per query to the log
        log-queries: no
        # Prints one line per reply to the log
        log-replies: no
        # Print log lines that say why queries return SERVFAIL to clients
        log-servfail: no
        # Print log lines to inform about local zone actions. Shows blocked domains
        log-local-actions: no
        # If this option is given, the use-syslog is option is set to "no"
        #logfile: /dev/null

        # |Privacy|
        # Deny queries of type ANY with an empty response
        deny-any: yes
        # Set the total number of unwanted replies to keep track of in every thread.
        # If it reaches the threshold, warning is printed and a defensive action is
        # taken, cache is cleared to flush away any poison
        # Suggested value is 10000000, default is 0 (turned off)
        unwanted-reply-threshold: 10000
        # Rotates RRSet order in response (the pseudo-random number is taken from
        # the query ID, for speed and thread safety)
        rrset-roundrobin: yes
        # Send minimum amount of information to upstream servers to enhance privacy
        qname-minimisation: yes
        # Do no insert authority/additional sections into response messages when
        # those sections are not required. This reduces response size significantly
        # and may avoid TCP fallback for some responses. It may speedup slightly.
        minimal-responses: yes
        # Refuse id.server and hostname.bind queries
        hide-identity: yes
        # Report this identity rather than the hostname of the server.
        identity: "DNS"
        # Refuse version.server and version.bind queries
        hide-version: yes
        # Control which clients are allowed to make (recursive) queries to this
        # server. By default everything is refused, except for localhost
        access-control: 127.0.0.0/8 allow
        access-control: 192.168.3.0/24 allow
        # Enforce privacy of these addresses. Strips them away from answers.
        # It may cause DNSSEC validation to additionally mark it as bogus.
        # Protects against DNS Rebinding
        private-address: 192.168.3.0/24

        # |Block|
        # Define tags that can be used with local-zone and access-control
        #define-tag: "school"
        # Assign tags to access-control elements. IPs using this access control
        # element use localzones that are tagged with one of these tags
        #access-control-tag: 10.1.1.30 "school"
        #access-control-tag: 10.1.1.32 "school"
        # Configure local-zone for filtered block
        #local-zone: "youtube.com" always_null
        #local-zone: "m.youtube.com" always_null
        # Assign tags to localzones. Tagged localzones will only be applied when
        # the used access-control element has a matching tag
        #local-zone-tag: youtube.com school
        #local-zone-tag: m.youtube.com school

        # |Modules|
        # List of module names separated by spaces. Order of modules is critical,
        # order decides the order of processing. Default is "validator iterator".
        # Added cachedb, should be just before the iterator.
        module-config: "validator cachedb iterator"

# Cache DB Module Options
cachedb:
        # Backend db name. Default db is in-memory backend named "testframe". Use redis
        backend: redis
        # Seed to calculate hash value from query information. Default is "default"
        #secret-seed: "unbound-config"

        # |Redis|
        # Socket
        redis-server-path: "/var/run/redis/redis.sock"
        # IP address of redis server. Default is 127.0.0.1
        #redis-server-host: 127.0.0.1
        # TCP port number of redis server. Default is 6379
        #redis-server-port: 6379
        # Period until unbound waits for response from redis sever. Default is 100ms
        redis-timeout: 100
        # Redis record expiration. If yes, unbound sets timeout for redis records so
        # that redis can evict expired keys automatically. If unbound is configured
        # with serve-expired this option internally reverts to no. Default is no
        redis-expire-records: no

# Remote Control Options
remote-control:
        # Enable remote control. If enabled unbound-control can be used. Default is no
        control-enable: yes
        #control-interface: /run/unbound.ctl
``` 

Redis.conf

```
# Redis configuration file
#
# Redis must be started with the file path as first argument:
#
# ./redis-server /path/to/redis.conf

# Note on units: Memory size can be specified as 1k 5GB 4M and so forth. Units
# are case insensitive so 1GB 1Gb 1gB are all the same

################################## INCLUDES ###################################

# Include one or more other config files here. Useful if you have a standard
# template that goes to all Redis servers but also need to customize few per
# server settings. To override config options, use include as the last line
#
# include /path/to/other.conf

################################## MODULES #####################################

# Load modules at startup.
#
# loadmodule /path/to/other_module.so

################################## NETWORK #####################################

bind 127.0.0.1 -::1
protected-mode yes
#port 6379
port 0
tcp-backlog 511
timeout 0
tcp-keepalive 300
unixsocket /var/run/redis/redis.sock
unixsocketperm 777
################################# GENERAL #####################################

daemonize no
supervised systemd
pidfile /run/redis/redis-server.pid
# Log verbosity level (debug, verbose, notice, warning)
loglevel warning
#logfile /var/log/redis/redis-server.log
syslog-enabled yes
# Set the number of databases
databases 1
always-show-logo no

################################ SNAPSHOTTING  ################################

# RDB (Redis Database) Persistence
#
# Save the DB to disk - "save <seconds> <changes> [<seconds> <changes> ...]"
# Below option will save the DB:
#  * After 43200 secs (12 hrs) if at least 1 change was performed
#  * After 7200 secs (2 hrs) if at least 100 changes were performed
# save "" - Disable snapshotting with empty string
save 43200 1 7200 100
# By default Redis will stop accepting writes if RDB snapshots are enabled and
# the latest background save failed
stop-writes-on-bgsave-error no
# By default compression is enabled. If you want to save some CPU in the saving
# child set it to 'no'
rdbcompression no
# Checksum is placed at the end of the file. Makes it resistant to corruption
# but has performance hit (around 10%) when saving and loading RDB files. It
# can be disabled for maximum performances
rdbchecksum no
# The filename where to dump the DB
dbfilename dump.rdb
# Remove RDB files used by replication in instances without persistence
# enabled. Default is disabled. It ONLY WORKS in instances that have both AOF
# and RDB persistence disabled, otherwise is completely ignored.
rdb-del-sync-files no
# The working directory. DB will be written inside this dir, with the filename
# specified above using dbfilename directive. The Append Only File will also be
# created inside this directory.
dir /var/lib/redis

################################# REPLICATION #################################

replica-serve-stale-data yes
replica-read-only yes
repl-diskless-sync yes
repl-diskless-sync-delay 5
repl-diskless-load disabled
repl-disable-tcp-nodelay no
replica-priority 100

################################## SECURITY ###################################

# The ACL Log tracks failed commands and authentication events associated with
# ACLs. ACL Log is stored in memory. Define max entry length of ACL Log below
acllog-max-len 128

############################## MEMORY MANAGEMENT ################################

# Memory usage limit. When limit is reached Redis will try to remove keys based
# on selected eviction policy
maxmemory 4mb
# Maxmemory policy decides how Redis will select what to remove when maxmemory
# is reached. LRU means Least Recently Used
maxmemory-policy allkeys-lru
# LRU, LFU and minimal TTL sample size. Default of 5 produces good enough
# results. 10 Approximates very closely true LRU but costs more CPU. 3 is
# faster but not very accurate.
# maxmemory-samples 5

############################# LAZY FREEING ####################################

lazyfree-lazy-eviction no
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
replica-lazy-flush no
lazyfree-lazy-user-del no
lazyfree-lazy-user-flush no

############################ KERNEL OOM CONTROL ##############################

oom-score-adj no
oom-score-adj-values 0 200 800

#################### KERNEL transparent hugepage CONTROL ######################

disable-thp yes

############################## APPEND ONLY MODE ###############################

# AOF (Append Only File) Persistence
#
appendonly no
appendfilename "appendonly.aof"
appenddirname "appendonlydir"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
aof-use-rdb-preamble yes
aof-timestamp-enabled no

################################## SLOW LOG ###################################

slowlog-log-slower-than 10000
slowlog-max-len 16

################################ LATENCY MONITOR ##############################

# Default is disabled
latency-monitor-threshold 0

############################# EVENT NOTIFICATION ##############################

# Default is disabled
notify-keyspace-events ""

############################### ADVANCED CONFIG ###############################

hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
list-compress-depth 0
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
hll-sparse-max-bytes 3000
stream-node-max-bytes 4096
stream-node-max-entries 100
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
dynamic-hz yes
aof-rewrite-incremental-fsync yes
rdb-save-incremental-fsync yes

########################### ACTIVE DEFRAGMENTATION #######################

# Jemalloc background thread for purging will be enabled by default
jemalloc-bg-thread yes
```
