### ISSUE TITLE
[FR] Allow multiple names in forward-zone

### ISSUE THREAD

**Issue by jaredmontoya** [NLnetLabs/unbound#1248]
I noticed that this was already mentioned in 2019 on https://lists.nlnetlabs.nl/pipermail/unbound-users/2019-February/005955.html
But there was never an answer except: "just write a script to generate duplicate forward-zones with names you want"
Which no one should have to do.

**Current behavior**
specifying multiple names per forward-zone leads to an error

**Describe the desired feature**
Make unbound treat this:
```yaml
forward-zone:
  name: "ygg.."
  name: "anon."
  forward-addr: 192.0.2.53
  forward-addr: 2001:db8::53
```
The same way as this:
```yaml
forward-zone:
  name: "ygg.."
  forward-addr: 192.0.2.53
  forward-addr: 2001:db8::53

forward-zone:
  name: "anon."
  forward-addr: 192.0.2.53
  forward-addr: 2001:db8::53
```

**Potential use-case**
- Whatever people said in https://lists.nlnetlabs.nl/pipermail/unbound-users/2019-February/005955.html
- Easily assigning multiple top level domains to be resolved only by a list of specialised resolvers that are the only ones able to resolve them without having to create a separate forward-zone with a duplicate of said list of resolvers for each top level domain. https://github.com/Revertron/Alfis is one such resolver.
