### ISSUE TITLE
`send failed: Socket is not connected` and `remote address is 0.0.0.0 port 53`

### ISSUE THREAD

**Issue by catap** [NLnetLabs/unbound#1254]
**Describe the bug**
I just discovered in logs of two machines which runs the same version of unbound but in different countries the same logs like:
```
Mar 21 22:05:34 mx2 unbound: [99981:0] notice: send failed: Socket is not connected
Mar 21 22:05:34 mx2 unbound: [99981:0] notice: remote address is 0.0.0.0 port 53
Mar 21 22:05:34 mx2 unbound: [99981:0] notice: send failed: Socket is not connected
Mar 21 22:05:34 mx2 unbound: [99981:0] notice: remote address is 0.0.0.0 port 53
Mar 21 22:05:34 mx2 unbound: [99981:0] notice: send failed: Socket is not connected
Mar 21 22:05:34 mx2 unbound: [99981:0] notice: remote address is 0.0.0.0 port 53
Mar 21 22:05:34 mx2 unbound: [99981:0] notice: send failed: Socket is not connected
Mar 21 22:05:34 mx2 unbound: [99981:0] notice: remote address is 0.0.0.0 port 53
Mar 21 22:05:34 mx2 unbound: [99981:0] notice: send failed: Socket is not connected
Mar 21 22:05:34 mx2 unbound: [99981:0] notice: remote address is 0.0.0.0 port 53
```

It had happened 8 times for last 2 days, each time a bulk of such logs.

I don't touch, and it seems works as expected but logs quite confusing.

**To reproduce**
Have no idea.

**Expected behavior**
No such wired logs I think, and no attempt to connect to `0.0.0.0`.

**System:**
 - Unbound version: 1.21.0
 - OS: OpenBSD 7.5
 - `unbound -V` output:
```
Version 1.21.0

Configure line: --enable-allsymbols --with-ssl=/usr --with-libevent=/usr --with-libexpat=/usr --without-pythonmodule --with-chroot-dir=/var/unbound --with-pidfile= --with-rootkey-file=/var/unbound/db/root.key --with-conf-file=/var/unbound/etc/unbound.conf --with-username=_unbound --disable-shared --disable-explicit-port-randomisation --without-pthreads
Linked libs: pluggable-libevent 1.4.15-stable (it uses kqueue), LibreSSL 4.0.0
Linked modules: dns64 respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Additional information**
Used config:
```
server:
        # Bind stricly to lo0
        interface: 127.0.0.1
        interface: ::1

        # I haven't got IPv6 on this machines, but OS supports it
        # so, it may lead to random: exceeded the maximum number of sends
        # See: https://github.com/NLnetLabs/unbound/issues/908
        do-ip6: no

        # Allow access only from localhost
        access-control: 0.0.0.0/0 refuse
        access-control: 127.0.0.0/8 allow
        access-control: ::0/0 refuse
        access-control: ::1 allow

        # Do not anounce used software
        hide-identity: yes
        hide-version: yes

        # Perform DNSSEC validation.
        auto-trust-anchor-file: "/var/unbound/db/root.key"

        # Some RBL DNS servers may treats minimized request as part of DDoS (default yes)
        qname-minimisation: no
        # Some RBL DNS zones have broken DNSSEC, yeah
        aggressive-nsec: no

        # Unbound try to not harm DNS infrastrucure and make requests quite gently.
        # Some RBL DNS servers usually overloaded, whcih may lead to ban it up to 24h
        # when it not well from Unbound point of view, or return SERVFAIL instead desired result.
        # See: https://github.com/NLnetLabs/unbound/issues/362
        # So, here I bypassing unbound ban list for upstream (default no)
        infra-keep-probing: yes
        # decrease upper limit for dynamic retransmit timeout to 15 seconds (default 2 minutes)
        infra-cache-max-rtt: 15000
        # and decrease the host cached roundtrip times to enforce retry (default 900 seconds)
        # keep in mind that value bigger leads to errors, and smaller increase network usage
        infra-host-ttl: 5

        # Discard requests after 5 minutes (default 19 seconds)
        discard-timeout: 300000

        # Disable any wait quereis limit (default 1000)
        wait-limit: 0

remote-control:
        control-enable: yes
        control-interface: /var/run/unbound.sock
```
