### ISSUE TITLE
DoT TLS resumption / stream reuse

### ISSUE THREAD

**Issue by mrpops2ko** [NLnetLabs/unbound#1271]
Looking at the previously closed tickets, the issue likely spans into / is related to 

https://github.com/NLnetLabs/unbound/issues/516
https://github.com/NLnetLabs/unbound/pull/283
https://github.com/NLnetLabs/unbound/issues/1045
https://github.com/NLnetLabs/unbound/issues/47

**Describe the bug**
I have set unbound up to forward upstream to cloudflare and effectively work as a forwarder with caching. I am using DoT and observing that the already established TLS connections are only partially being reused for queries. 

Here is my understanding, in the hopes of aligning better on the bug. I have a FTTP connection, 2ms to my first hop WAN gateway outside my home and 5ms upstream to cloudflare. Using plain UDP DNS requests to cloudflare, I can achieve sub 10ms responses.

In unbound I have set up all my upstream DNS queries to use DoT to cloudflare. My local LAN client queries to myself use plaintext UDP port 53.  

It is my understanding that with DoT, after having done the 3 way handshake for TLS, in a properly working config those responses should be similar or at least slightly higher. lets say sub 16ms. 

Instead what I am noticing is that the connection is being constantly remade and this means that when recursive queries upstream to cloudflare happen, I am experiencing anywhere from 30ms to 250ms on queries.  

**Expected behavior**
98% or more of my upstream queries should be sub 16ms when contacting cloudflare and reusing the TLS TCP connection. This should be observable from the histogram breakdown in unbound for recursive upstream queries.  
 
**System:**
I am virtualising pfsense, along with passthrough of an intel x520 10gb nic.
I have more than enough horse power on this machine
```
CPU Type | AMD Ryzen 9 7950X 16-Core Processor
4 CPUs : 1 package(s) x 4 core(s)
```

 - Unbound version:
```
[24.11-RELEASE][admin@pfSense.home.arpa]/var/unbound: unbound -V
Version 1.22.0

Configure line: --with-libexpat=/usr/local --with-ssl=/usr --enable-dnscrypt --disable-dnstap --with-dynlibmodule --enable-ecdsa --disable-event-api --enable-gost --with-libevent --with-pythonmodule=yes --with-pyunbound=yes ac_cv_path_SWIG=/usr/local/bin/swig LDFLAGS=-L/usr/local/lib --disable-subnet --disable-tfo-client --disable-tfo-server --with-pthreads --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/share/man --infodir=/usr/local/share/info/ --build=amd64-portbld-freebsd15.0
Linked libs: libevent 2.1.12-stable (it uses kqueue), OpenSSL 3.0.14 4 Jun 2024
Linked modules: dns64 python dynlib respip validator iterator
DNSCrypt feature available

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```
 - OS:
 ```
[24.11-RELEASE][admin@pfSense.home.arpa]/var/unbound: uname -a
FreeBSD pfSense.home.arpa 15.0-CURRENT FreeBSD 15.0-CURRENT #0 plus-RELENG_24_11-n256407-1bbb3194162: Fri Nov 22 05:08:46 UTC 2024     root@freebsd:/var/jenkins/workspace/pfSense-Plus-snapshots-24_11-main/obj/amd64/AKWlAIiM/var/jenkins/workspace/pfSense-Plus-snapshots-24_11-main/sources/FreeBSD-src-plus-RELENG_24_11/amd64.amd64/sys/pfSense amd64
```

**Additional information**
I'm using these 3 commands mostly to track and verify my observations, to really drill down on what is happening

```
[24.11-RELEASE][admin@pfSense.home.arpa]/root: sh -c 'unbound-control -c /var/unbound/unbound.conf stats | tee /tmp/unbound.stats.tmp | awk '\''BEGIN { sections["Query Totals & Cache"] = "^total\\.num\\.(queries|cache|prefetch|expired|recursivereplies|queries_timed_out)"; sections["Query Types"] = "^num\\.query\\.type"; sections["Transport Protocols"] = "^num\\.query\\.(tcp|udp|tls|https|ipv6)"; sections["DNSSEC Validation"] = "^num\\.answer\\.(secure|bogus)|^num\\.rrset\\.bogus"; sections["Response Codes"] = "^num\\.answer\\.rcode(\\.|$)|^num\\.answer\\.rcode\\.nodata"; sections["Errors / Threats"] = "^(unwanted|ratelimited|queries_timed_out|total\\.num\\.queries_timed_out)"; sections["Memory & Cache Stats"] = "^mem\\.cache|^cache\\.(count|max_collisions)"; } { for (s in sections) { if ($0 ~ sections[s]) { split($0, kv, "="); if (kv[2] + 0 > 0) { if (!(s in seen)) { print "\n\033[1;34m== " s " ==\033[0m"; seen[s] = 1; } printf "\033[0;36m%-35s:\033[0;33m %-10s\033[0m\n", kv[1], kv[2]; } } } }'\''; echo ""; echo -e "\033[1;34m== Response Summary ==\033[0m"; noerror=$(grep "^num\.answer\.rcode\.NOERROR=" /tmp/unbound.stats.tmp | cut -d= -f2); nxdomain=$(grep "^num\.answer\.rcode\.NXDOMAIN=" /tmp/unbound.stats.tmp | cut -d= -f2); servfail=$(grep "^num\.answer\.rcode\.SERVFAIL=" /tmp/unbound.stats.tmp | cut -d= -f2); nodata=$(grep "^num\.answer\.rcode\.nodata=" /tmp/unbound.stats.tmp | cut -d= -f2); totalresp=$(echo "$noerror + $nxdomain + $servfail + $nodata" | bc); printf "\033[0;36mTotal responses:\033[0;33m %s\033[0m\n" "$totalresp"; printf "\033[0;36mNOERROR:\033[0;33m %.2f%%\033[0m\n" $(echo "$noerror * 100 / $totalresp" | bc -l); printf "\033[0;36mNXDOMAIN:\033[0;33m %.2f%%\033[0m\n" $(echo "$nxdomain * 100 / $totalresp" | bc -l); printf "\033[0;36mSERVFAIL:\033[0;33m %.2f%%\033[0m\n" $(echo "$servfail * 100 / $totalresp" | bc -l); printf "\033[0;36mNODATA:\033[0;33m %.2f%%\033[0m\n" $(echo "$nodata * 100 / $totalresp" | bc -l); echo ""; echo -e "\033[1;34m== Additional Stats ==\033[0m"; totalq=$(grep "^total.num.queries=" /tmp/unbound.stats.tmp | cut -d= -f2); cachehits=$(grep "^total.num.cachehits=" /tmp/unbound.stats.tmp | cut -d= -f2); cachemiss=$(grep "^total.num.cachemiss=" /tmp/unbound.stats.tmp | cut -d= -f2); prefetch=$(grep "^total.num.prefetch=" /tmp/unbound.stats.tmp | cut -d= -f2); rec=$(grep "^total.num.recursivereplies=" /tmp/unbound.stats.tmp | cut -d= -f2); nonrec=$(echo "$totalq - $rec" | bc); printf "\033[0;36mTotal queries:\033[0;33m %s\033[0m\n" "$totalq"; printf "\033[0;36mCache Hit %%:\033[0;33m %.2f%%\033[0m\n" $(echo "$cachehits * 100 / $totalq" | bc -l); printf "\033[0;36mCache Miss %%:\033[0;33m %.2f%%\033[0m\n" $(echo "$cachemiss * 100 / $totalq" | bc -l); printf "\033[0;36mPrefetch usage %%:\033[0;33m %.2f%%\033[0m\n" $(echo "$prefetch * 100 / $totalq" | bc -l); printf "\033[0;36mNon-recursive estimate (fast answers):\033[0;33m %s (%.2f%%)\033[0m\n" "$nonrec" $(echo "$nonrec * 100 / $totalq" | bc -l); printf "\033[0;36mRecursive rate:\033[0;33m %.2f%%\033[0m\n" $(echo "$rec * 100 / $totalq" | bc -l); echo ""; echo -e "\033[1;34m== Latency Histogram Breakdown (recursive queries only) ==\033[0m"; total=$(grep "^total.num.recursivereplies=" /tmp/unbound.stats.tmp | cut -d= -f2); grep "^histogram\\." /tmp/unbound.stats.tmp | awk -v total="$total" -F"[.=]" '\''{ s=$2*1000000+$3; e=$5*1000000+$6; c=$NF; if (c>0 && s>=8192) { ms1=int(s/1000); ms2=int(e/1000); p=(c/total)*100; cum+=p; printf "\033[0;36m%4d-%4d ms:\033[0m \033[0;33m%6d\033[0m \033[0;36mqueries\033[0m (\033[0;33m%.2f%%\033[0m, \033[0;36mcumulative\033[0m: \033[0;33m%.2f%%\033[0m)\n", ms1, ms2, c, p, cum } }'\''; echo ""'

== Query Totals & Cache ==
total.num.queries                  : 77472
total.num.cachehits                : 73093
total.num.cachemiss                : 4379
total.num.prefetch                 : 25560
total.num.expired                  : 20285
total.num.recursivereplies         : 4378

== Memory & Cache Stats ==
mem.cache.rrset                    : 1121820
mem.cache.message                  : 1220979

== Query Types ==
num.query.type.A                   : 54903
num.query.type.CNAME               : 39
num.query.type.SOA                 : 3
num.query.type.PTR                 : 102
num.query.type.MX                  : 77
num.query.type.TXT                 : 17
num.query.type.AAAA                : 18051
num.query.type.SRV                 : 8
num.query.type.SVCB                : 90
num.query.type.HTTPS               : 4182

== Transport Protocols ==
num.query.tcp                      : 2
num.query.tcpout                   : 1267

== Response Codes ==
num.answer.rcode.NOERROR           : 76422
num.answer.rcode.SERVFAIL          : 421
num.answer.rcode.NXDOMAIN          : 628
num.answer.rcode.nodata            : 15630

== Response Summary ==
Total responses: 93101
NOERROR: 82.09%
NXDOMAIN: 0.67%
SERVFAIL: 0.45%
NODATA: 16.79%

== Additional Stats ==
Total queries: 77472
Cache Hit %: 94.35%
Cache Miss %: 5.65%
Prefetch usage %: 32.99%
Non-recursive estimate (fast answers): 73094 (94.35%)
Recursive rate: 5.65%

== Latency Histogram Breakdown (recursive queries only) ==
   8-  16 ms:    576 queries (13.16%, cumulative: 13.16%)
  16-  32 ms:    551 queries (12.59%, cumulative: 25.74%)
  32-  65 ms:   1012 queries (23.12%, cumulative: 48.86%)
  65- 131 ms:   1204 queries (27.50%, cumulative: 76.36%)
 131- 262 ms:    586 queries (13.39%, cumulative: 89.74%)
 262- 524 ms:    167 queries (3.81%, cumulative: 93.56%)
 524-1000 ms:     15 queries (0.34%, cumulative: 93.90%)
1000-2000 ms:      8 queries (0.18%, cumulative: 94.08%)
```

from this we can the histogram breakdown showing a good 50% of all upstream cloudflare requests are resulting in latencies exceeding 65ms, which shouldn't be the case if tls resumption / reusing the socket was working properly. 

Additionally no meaningful data can be gleamed on frequency of established connection port change, I am using the following command to monitor

```
[24.11-RELEASE][admin@pfSense.home.arpa]/var/unbound: sh -c 'i=0; old=""; start=$(date +%s); seen=""; while :; do now=$(date +%s); p=$(netstat -an | grep "\.853" | grep ESTABLISHED | awk '\''{print $4}'\'' | awk -F. '\''{print $(NF)}'\''); [ "$p" != "$old" ] && [ -n "$p" ] && { echo "Active port change #$i: $old -> $p (after $((now - start))s)"; i=$((i+1)); old=$p; start=$now; }; t=$(netstat -an | grep "\.853" | grep TIME_WAIT | awk '\''{print $4}'\'' | awk -F. '\''{print $(NF)}'\'' | sort -u); n=""; for x in $t; do echo "$seen" | grep -q "\\b$x\\b" || { n="$n $x"; seen="$seen $x"; }; done; [ -n "$n" ] && echo "New TIME_WAIT ports observed:$n"; sleep 1; done'
Active port change #0:  -> 29019 (after 0s)
New TIME_WAIT ports observed: 29019
Active port change #1: 29019 -> 36185 (after 33s)
Active port change #2: 36185 -> 22974 (after 1s)
Active port change #3: 22974 -> 1488 (after 24s)
New TIME_WAIT ports observed: 22974
New TIME_WAIT ports observed: 12541 1488 3266 37825 54854
Active port change #4: 1488 -> 8171 (after 38s)
New TIME_WAIT ports observed: 8171
Active port change #5: 8171 -> 33761 (after 55s)
Active port change #6: 33761 -> 26489 (after 29s)
New TIME_WAIT ports observed: 33761 42698
Active port change #7: 26489 -> 35059 (after 1s)
New TIME_WAIT ports observed: 26489
Active port change #8: 35059 -> 20331 (after 15s)
Active port change #9: 20331 -> 22772 (after 34s)
New TIME_WAIT ports observed: 20331 27201
Active port change #10: 22772 -> 63133 (after 65s)
Active port change #11: 63133 -> 8546 (after 7s)
New TIME_WAIT ports observed: 63133
Active port change #12: 8546 -> 44629 (after 7s)
New TIME_WAIT ports observed: 8546
Active port change #13: 44629 -> 30171 (after 5s)
Active port change #14: 30171 -> 17357 (after 21s)
New TIME_WAIT ports observed: 30171
Active port change #15: 17357 -> 44836 (after 19s)
New TIME_WAIT ports observed: 44836
Active port change #16: 44836 -> 16596 (after 51s)
Active port change #17: 16596 -> 7569 (after 4s)
New TIME_WAIT ports observed: 16596
Active port change #18: 7569 -> 43006 (after 46s)
New TIME_WAIT ports observed: 7569
New TIME_WAIT ports observed: 43006
Active port change #19: 43006 -> 49679 (after 9s)
New TIME_WAIT ports observed: 11430
Active port change #20: 49679 -> 64311 (after 14s)
New TIME_WAIT ports observed: 49679
Active port change #21: 64311 -> 46392 (after 19s)
New TIME_WAIT ports observed: 46392
Active port change #22: 46392 -> 24614 (after 34s)
Active port change #23: 24614 -> 60887 (after 14s)
New TIME_WAIT ports observed: 24614
Active port change #24: 60887 -> 11284 (after 62s)
New TIME_WAIT ports observed: 60887
 New TIME_WAIT ports observed: 11284
Active port change #25: 11284 -> 24222 (after 90s)
New TIME_WAIT ports observed: 62882
New TIME_WAIT ports observed: 24222
Active port change #26: 24222 -> 48255 (after 49s)
Active port change #27: 48255 -> 52789 (after 9s)
New TIME_WAIT ports observed: 42799 44475 48255 57251
New TIME_WAIT ports observed: 52789
Active port change #28: 52789 -> 18897 (after 19s)
Active port change #29: 18897 -> 53503 (after 22s)
New TIME_WAIT ports observed: 18897 47208
Active port change #30: 53503 -> 45822 (after 39s)
New TIME_WAIT ports observed: 53503
Active port change #31: 45822 -> 16653 (after 12s)
Active port change #32: 16653 -> 15309 (after 80s)
Active port change #33: 15309 -> 52021 (after 15s)
New TIME_WAIT ports observed: 15309
Active port change #34: 52021 -> 16508 (after 17s)
New TIME_WAIT ports observed: 16508
Active port change #35: 16508 -> 12036 (after 100s)
New TIME_WAIT ports observed: 12036
Active port change #36: 12036 -> 16705 (after 20s)
Active port change #37: 16705 -> 7134 (after 41s)
New TIME_WAIT ports observed: 16705
Active port change #38: 7134 -> 3698 (after 26s)
New TIME_WAIT ports observed: 7134
Active port change #39: 3698 -> 12272 (after 63s)
New TIME_WAIT ports observed: 3698
Active port change #40: 12272 -> 12998 (after 21s)
New TIME_WAIT ports observed: 12272
```

attached is my unbound.conf file, due to the way pfsense allocates the num-threads (based upon cpu's) I had to add an additional custom config at the bottom since i cannot edit it at the top without pfsense overwriting it. this shouldn't be an issue though because the last values should be the ones which are applied. when i remove the bottom num-threads, then the amount of established connections and associated information increases

```
[24.11-RELEASE][admin@pfSense.home.arpa]/var/unbound: cat unbound.conf
##########################
# Unbound Configuration
##########################

##
# Server configuration
##
server:

chroot: /var/unbound
username: "unbound"
directory: "/var/unbound"
pidfile: "/var/run/unbound.pid"
use-syslog: yes
port: 53
verbosity: 1
hide-identity: yes
hide-version: yes
harden-glue: yes
do-ip4: yes
do-ip6: no
do-udp: yes
do-tcp: yes
do-daemonize: yes
module-config: "iterator"
unwanted-reply-threshold: 0
num-queries-per-thread: 2048
jostle-timeout: 1000
infra-keep-probing: yes
infra-host-ttl: 900
infra-cache-numhosts: 200000
outgoing-num-tcp: 50
incoming-num-tcp: 50
edns-buffer-size: 1432
cache-max-ttl: 86400
cache-min-ttl: 0
harden-dnssec-stripped: no
msg-cache-size: 512m
rrset-cache-size: 1024m

num-threads: 4
msg-cache-slabs: 4
rrset-cache-slabs: 4
infra-cache-slabs: 4
key-cache-slabs: 4
outgoing-range: 4096
#so-rcvbuf: 4m

prefetch: yes
prefetch-key: no
use-caps-for-id: no
serve-expired: yes
sock-queue-timeout: 0
aggressive-nsec: no
# Statistics
# Unbound Statistics
statistics-interval: 0
extended-statistics: yes
statistics-cumulative: yes

# TLS Configuration
tls-cert-bundle: "/etc/ssl/cert.pem"

# Interface IP addresses to bind to
interface: 192.168.1.1
interface: 192.168.20.1
interface: 192.168.60.1
interface: 192.168.50.1
interface: 127.0.0.1
interface: ::1

# Outgoing interfaces to be used
outgoing-interface: {home_IP_removed}

# DNS Rebinding
# For DNS Rebinding prevention
private-address: 127.0.0.0/8
private-address: 10.0.0.0/8
private-address: ::ffff:a00:0/104
private-address: 172.16.0.0/12
private-address: ::ffff:ac10:0/108
private-address: 169.254.0.0/16
private-address: ::ffff:a9fe:0/112
private-address: 192.168.0.0/16
private-address: ::ffff:c0a8:0/112
private-address: fd00::/8
private-address: fe80::/10

# Access lists
include: /var/unbound/access_lists.conf

# Static host entries
include: /var/unbound/host_entries.conf

# Domain overrides
include: /var/unbound/domainoverrides.conf
# Forwarding
forward-zone:
	name: "."
	forward-tls-upstream: yes
	forward-addr: 1.1.1.1@853#one.one.one.one


# Unbound custom options
server:
    tcp-idle-timeout: 180000
    tls-session-ticket-keys: "/var/unbound/tls-session-ticket.key"
    num-threads: 1
    msg-cache-slabs: 1
    rrset-cache-slabs: 1
    infra-cache-slabs: 1
    key-cache-slabs: 1
#    outgoing-range: 1
#    outgoing-port-permit: 12345
#    edns-tcp-keepalive: yes
#    edns-tcp-keepalive-timeout: 180000

module-config: "respip validator iterator"
    rpz:
        name: "."
        zonefile: "/var/unbound/rpz.local"

server:include: /var/unbound/pfb_dnsbl.*conf
###
# Remote Control Config
###
include: /var/unbound/remotecontrol.conf
```

i tested the commented out settings in the hopes of each of those fixing this issue, but none of them did
```
#    outgoing-range: 1
#    outgoing-port-permit: 12345
#    edns-tcp-keepalive: yes
#    edns-tcp-keepalive-timeout: 180000
```

any ideas where to go from here?
