### ISSUE TITLE
make uninstall not possible and unbound.conf not found during installation

### ISSUE THREAD

**Issue by Aura67** [NLnetLabs/unbound#1273]
Hello, when I wanted to compile the new version of unbound, the compiling script I wrote for it simply didn't work. I only wrote that it should change to the unbound folder and then change to the unbound-= version in order to then execute service unbound stop and then do make uninstall to install the new version of unbound, i.e. download and compile, and that doesn't work with 1.23.0. I had to do it manually and unbound told me that it couldn't find the unbound conf even though it already exists. It worked with 1.22.0.

and I found even more errors. I have a forward zone with quad9 which worked in 1.22.0 but unbound tells me this in version 1.23.0: 

Apr 24 17:01:51 AdGuardHome unbound[662]: [662:0] info: start of service (unbound 1.23.0).
Apr 24 17:04:27 AdGuardHome unbound[662]: [662:0] info: generate keytag query _ta-4f66-9728. NULL IN
Apr 24 18:54:28 AdGuardHome unbound[662]: [662:0] error: ssl handshake failed: channel closed
Apr 24 18:54:28 AdGuardHome unbound[662]: [662:0] notice: ssl handshake failed 9.9.9.9 port 53
Apr 24 18:54:39 AdGuardHome unbound[662]: [662:0] error: ssl handshake failed: channel closed
Apr 24 18:54:39 AdGuardHome unbound[662]: [662:0] notice: ssl handshake failed 9.9.9.9 port 53
Apr 24 18:54:50 AdGuardHome unbound[662]: [662:0] error: ssl handshake failed: channel closed
Apr 24 18:54:50 AdGuardHome unbound[662]: [662:0] notice: ssl handshake failed 149.112.112.112 port 53
Apr 24 18:55:00 AdGuardHome unbound[662]: [662:0] error: ssl handshake failed: channel closed
Apr 24 18:55:00 AdGuardHome unbound[662]: [662:0] notice: ssl handshake failed 149.112.112.112 port 53

I have configured the forward zone correctly in unbound.

I've just downloaded version 1.22.0 again and tried make uninstall and it worked. Unbound 1.23.0 seems to have a problem with it and also a problem with the forward zone. I'm waiting for a new release with a bug fix. In the meantime, I'm using quad9 over TLS alone, since unbound would only send there with a forward zone, so it doesn't make a difference.

**Comment by gthess** [comment]
I can't comment on what happens with your script; maybe if you share it we can figure it out.

For the TLS connection, I see that port 53 is used there and that doesn't seem right. Can you share your forward configuration?

**Comment by Aura67** [comment]
yes i can here is my setup for the forward-zone:
```
# Certificates used to authenticate connections made upstream.
    tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt

# Enable  or disable sending the SNI extension on TLS connections.
    # Default is yes.  Changing the value requires a reload.
    tls-use-sni: yes

 # Set the list of ciphers to allow when serving TLS. Use "" for default ciphers
    tls-ciphers: “”

    # Set the list of ciphersuites to allow when serving TLS. This is for newer TLS 1.3 connections. Use "" for default ciphersuites.
    tls-ciphersuites: “”

forward-zone:
    # Forward all queries (except those in cache and local zone) to
    # upstream recursive servers
    name: "."
    forward-tls-upstream: yes
    forward-first: no
    # Queries to this forward zone use TLS
    forward-addr: 9.9.9.9@853#dns.quad9.net
    forward-addr: 149.112.112.112@853#dns.quad9.net
```
and the other options above were simply DNSSEC itself and a few others, but these had nothing to do with the forward zone
