### ISSUE TITLE
Cache / prefetch difference between 1.22 and 1.23

### ISSUE THREAD

**Issue by Delta1977** [NLnetLabs/unbound#1279]
Hi together,

I run unbound 1.22 for a while in docker without problems and get an Cache-rate from ~80 %

Now I move on to v1.23 and the cache-rate go down to <5%

The config is unchanged. 

Can someone give me a hint why the  Cacherate go down ?

**Comment by nshopik** [comment]
Yeah we also seeing weird results moving from 1.21.1 to 1.23 show drop from 80% to 50% or less for cache hit ratio.

**Comment by nshopik** [comment]
Looks like its related to this change https://github.com/NLnetLabs/unbound/issues/1175 due to change of serve-expired-client-timeout from 0 to 1800

**Comment by mattredact** [comment]
What is the solution to this? Reverting serve-expired-client-timeout back to 0?

**Comment by gthess** [comment]
I believe this is indeed because of the changes to the default value of `serve-expired-client-timeout` in 1.23.0; assuming that you are using `serve-expired`.

The old default behavior (value == 0) would use the expired cached record straight away and would count that as a cache hit answer.

The new default behavior (value == 1800, or any value > 0 for that matter) uses the expired answer only after resolution failed or resolution is taking a longer time than the configured `serve-expired-client-timeout` which is the suggested behavior as per RFC8767.
It doesn't count as a cache hit because it wasn't an immediate answer from the cache. It only counts as an expired answer.

There is a blog post that explains the two different modes of serve-expired operation in Unbound: https://blog.nlnetlabs.nl/some-country-for-old-men/ when RFC8767 was implemented.

**Comment by mattredact** [comment]
> I believe this is indeed because of the changes to the default value of `serve-expired-client-timeout` in 1.23.0; assuming that you are using `serve-expired`.
> 
> The old default behavior (value == 0) would use the expired cached record straight away and would count that as a cache hit answer.
> 
> The new default behavior (value == 1800, or any value > 0 for that matter) uses the expired answer only after resolution failed or resolution is taking a longer time than the configured `serve-expired-client-timeout` which is the suggested behavior as per RFC8767. It doesn't count as a cache hit because it wasn't an immediate answer from the cache. It only counts as an expired answer.
> 
> There is a blog post that explains the two different modes of serve-expired operation in Unbound: https://blog.nlnetlabs.nl/some-country-for-old-men/ when RFC8767 was implemented.

It definitely is. I changed back to 0 to test and my cache hit rate in my home network was around 86%. With 1800, it's down to about 50% at best.

**Comment by gthess** [comment]
Just for clarity, this means that ~35% of the cache hits are expired entries. This could mean that:
- a significant number of client queries get low TTL answers from upstream,
- client queries for cached items are not frequent enough so that `prefetch` could keep records fresh,

But in the end I don't see anything wrong with Unbound.

@Delta1977 's case (80% down to 5%) seems a bit curious but it all depends on the points I shared above.

**Comment by thezerowhisper** [comment]
Can @delta1977 share your config that gave you 80% plus cache hits.
Looking to fine-tune my setup as max i am able to get is 50% hits even when i have basically same set of websites i visit daily

**Comment by Delta1977** [comment]
I haven't this old config. But as I remember it was Standard values. 
We use it as resolver for a Company network wich use many Cloudservices. So many requests for the same URL's.

**Comment by mattredact** [comment]
@diamondfdk I can share mine. Here you go. This is 81% cache hit running for a few days. I'm also using Redis as a L2 cache, you but you can ignore/comment that out. 

```
server:
  interface: 127.0.0.1
  port: 5335
  ip-freebind: yes
  statistics-interval: 0
  extended-statistics: yes
  statistics-cumulative: yes
  do-ip4: yes
  do-ip6: no
  do-udp: yes
  do-tcp: yes
  prefer-ip6: no
  auto-trust-anchor-file: "/var/lib/unbound/root.key"
  root-hints: "/var/lib/unbound/root.hints"
  do-daemonize: no
  num-threads: 1
  so-reuseport: yes
  edns-buffer-size: 1232
  so-rcvbuf: 4m
  so-sndbuf: 4m
  msg-cache-slabs: 1
  rrset-cache-slabs: 1 
  infra-cache-slabs: 1
  key-cache-slabs: 1
  key-cache-size: 16m
  msg-cache-size: 128m
  rrset-cache-size: 256m
  neg-cache-size: 4m
  prefetch: yes
  prefetch-key: yes
  serve-expired: yes
  serve-expired-reply-ttl: 30
  serve-expired-ttl: 86400
  serve-expired-client-timeout: 0
  cache-min-ttl: 3600
  cache-max-ttl: 86400
  harden-glue: yes
  harden-large-queries: yes
  harden-dnssec-stripped: yes
  harden-algo-downgrade: yes
  harden-short-bufsize: yes
  verbosity: 0
  log-queries: no
  log-replies: no
  log-servfail: no
  log-local-actions: no
  deny-any: yes
  unwanted-reply-threshold: 10000
  rrset-roundrobin: yes
  qname-minimisation: yes
  minimal-responses: yes
  hide-identity: yes
  identity: "DNS"
  hide-version: yes
  access-control: 127.0.0.0/8 allow
  access-control: 10.10.100.0/24 allow
  private-address: 10.0.0.0/8
  private-address: 172.16.0.0/12
  module-config: "validator cachedb iterator"

cachedb:
  backend: redis
  redis-server-path: "/var/run/redis/redis.sock"
  redis-timeout: 100
  redis-expire-records: no
  cachedb-check-when-serve-expired: no

remote-control:
  control-enable: yes
  control-interface: /run/unbound.ctl
```

**Comment by gthess** [comment]
This seems to be a non-issue; already answered that the default value change of `serve-expired-client-timeout` and low upstream TTL values could cause the difference in behavior.

**Comment by snrubthinks** [comment]
Should the documentation be updated to reflect this change? The [example](https://unbound.docs.nlnetlabs.nl/en/latest/topics/core/serve-stale.html) for a higher cache hit approach does not work as given because of the change in `serve-expired-client-timeout`. Instead:

```
server:
    prefetch: yes
    serve-expired: yes
    serve-expired-ttl: 86400  # one day, in seconds
    serve-expired-client-timeout: 0
```
