### ISSUE TITLE
log-destaddr fail on long ipv6 addresses

### ISSUE THREAD

**Issue by andreasschulze** [NLnetLabs/unbound#1282]
**Describe the bug**

using the statement `log-destaddr: yes` produce unexpected data

**To reproduce**

the following will create 3 files, `docker-compose.yml`, `Dockerfile` and `unbound.conf`. Then run `docker-compose up -d && docker-compose logs -f`. In a second terminal, call `docker-compose exec unbound bash`. Inside the container, you can call `kdig -6 @unbound test. txt`  

Watch the other terminal showing the query log. Notice, the lines end with `2001:db8::2 53` which are the unbound's service-address and port.

now stop unbound in the first terminal and change the service address:
`sed -i -e 's/2001:db8::2/2001:db8::1234:1234:1234:1234/g' *`

Start the server again and fire up some queries in the second terminal. Notice, the log lines end now different, the service-adress field show not the expected data.

```
cd /tmp
cat <<EOF > docker-compose.yml
networks:
  internal_network:
    internal: true
    enable_ipv6: true
    ipam:
      config:
      - subnet: 2001:db8::/64
      - subnet: 192.0.2.0/24

services:
  unbound:
    build:
      context: .
    entrypoint: unbound
    hostname: unbound
    image: localhost/unbound
    networks:
      internal_network:
        ipv4_address: 192.0.2.2
        ipv6_address: 2001:db8::2
    volumes:
    - ./:/etc/unbound/unbound.conf.d:ro
EOF

cat <<EOF > Dockerfile
FROM debian:trixie-slim
RUN apt-get -qq -y update
RUN apt-get -qq -y install --no-install-recommends unbound knot-dnsutils
EOF

cat <<"EOF" > unbound.conf
server:
        chroot: ""
        do-daemonize: no
        do-ip6: yes
        logfile: ""
        use-caps-for-id: yes
        interface: 192.0.2.2
        interface: 2001:db8::2
        access-control: 192.0.2.0/24 allow
        access-control: 2001:db8::/64 allow
        log-destaddr: yes
        log-replies: yes
        local-zone: test. static
        local-data: "test. txt test"
EOF

```
**Additional information**
see https://lists.nlnetlabs.nl/pipermail/unbound-users/2024-March/008273.html for my similar problem description without this detailed steps to reproduce ...
