### ISSUE TITLE
Shared memory statistics are not reliable

### ISSUE THREAD

**Issue by svartalf** [NLnetLabs/unbound#152]
`unbound` statistics exposed via shared memory are changing unexpectedly even if server itself does no work.

1. I had started a separate `unbound` server with the shm stats enabled:

```
server:
        verbosity: 1
        statistics-interval: 3

        shm-enable: yes
        shm-key: 11777

        statistics-cumulative: yes
        extended-statistics: yes

        num-threads: 3
```

2. Sent three requests to it:

```
$ dig @localhost example.com
 .. skipped a bunch of text for clarity
;; SERVER: ::1#53(::1)
 ..

$ dig @localhost example.org
 .. skipped
;; SERVER: ::1#53(::1)

$ @localhost example.net
 ..
;; SERVER: ::1#53(::1)
```

3. `unbound-control stats_noreset` shows that three IPv6 queries were issued:
```
$ unbound-control stats_noreset | grep num.query.ipv6
num.query.ipv6=3
```

4. `unbound-control stats_shm` shows zero IPv6 queries:
```
$ unbound-control stats_shm | grep num.query.ipv6
num.query.ipv6=0
```

I also noted that when both these commands are executed via `watch` command, most of the time `stats_shm` shows incorrect value, but blinks with correct value from time to time:

`$watch -n 0.5 "unbound-control stats_shm | grep ipv6 && unbound-control stats_noreset | grep ipv6"`

Other statistic metrics shows the same behavior, for example:
```
$ unbound-control stats_noreset | grep AD
num.query.flags.AD=3
$ unbound-control stats_shm | grep AD
num.query.flags.AD=0
```

Accessing the shared memory regions with `shmat`/`shmget` results in the same behavior.

I guess it happens because [`shm_main_run`](https://github.com/NLnetLabs/unbound/blob/ff92edcd410610e0f506e4daf0ffbad58ed01760/util/shm_side/shm_main.c#L218) function does not do the memory update atomically and read operations happen during the update process?
