### ISSUE TITLE
auth-zone exclude forward-zone for a subdomain

### ISSUE THREAD

**Issue by ab-fuze** [NLnetLabs/unbound#202]
If in the config file I have a:
- host: 10.0.0.1
```
auth-zone:
  name: "domain.ee"
  zonefile: "/zones/domain.ee.zone"

forward-zone:
  name: "sub.domain.ee"
  forward-addr: 10.0.0.1:5300

```

and the zone file contains 
```
$ORIGIN sub.domain.ee.
@                               NS        10.0.0.1

``` 
the forward is ignored if I query:
`host1.sub.domain.ee`

the log shows:
`domain sub.domain.ee. notexact notexist,`
