### ISSUE TITLE
Forever "Too many queries. dropping incoming query"

### ISSUE THREAD

**Issue by R4scal** [NLnetLabs/unbound#227]
Hi
We use unbound as caching recursive DNS on own site. Everything was fine, but one day our site lost internet connection for 2 minutes and resolving stop working. In logs
```
[1587561379] unbound[25416:0] debug: udp request from ip4 x.x.x.x port 52739 (len 16)
[1587561379] unbound[25416:0] debug: Too many queries. dropping incoming query.
```
The problem was not solved after recovery of the internet connnection in 5 or 15 minutes. The problem was solved only by restarting the unbound process.

Our config:
```
server:
    verbosity: 5
    interface: 0.0.0.0
    chroot: ""
    do-ip4: yes
    do-ip6: no
    num-threads: 1
    outgoing-range: 8192
    num-queries-per-thread: 4096
    logfile: /var/log/unbound.log
    pidfile: /var/run/unbound.pid
    hide-version: yes
    do-daemonize: yes
    access-control: 0.0.0.0/0 allow
    cache-min-ttl: 30
    serve-expired: yes
    serve-expired-ttl: 0
    serve-expired-ttl-reset: no
    сlient-timeout: 150
    prefetch: yes
    do-not-query-localhost: no
forward-zone:
  name: "."
  forward-addr: 8.8.8.8
  forward-addr: 8.8.4.4
forward-zone:
  name: "local.example.com"
  forward-addr: 127.0.0.1@5353
forward-zone:
  name: "consul.example.com"
  forward-addr: 127.0.0.1@8600
```

Versions:
```
unbound -V
Version 1.10.0

Configure line: --enable-fully-static LDFLAGS=-static --disable-flto --with-libevent
Linked libs: libevent 2.1.8-stable (it uses epoll), OpenSSL 1.1.1d  10 Sep 2019
Linked modules: dns64 respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```
