### ISSUE TITLE
`serve-expired-client-timeout` cause `num_reply_states` incorrectly decrease to below 0

### ISSUE THREAD

**Issue by yihtak** [NLnetLabs/unbound#232]
In v1.10, when using `serve-expired-client-timeout`, seeing `num_reply_states` incorrectly decrease to below 0 and flipped and becomes huge unsigned number. This immediately stop unbound from processing any new request due to `num_reply_states > max_reply_states`.

### Logs
In log found:
```
debug: Too many queries. dropping incoming query.
```
and
```
info: mesh_run: end 10 recursion states (4294967295 with reply, 7 detached), 0 waiting replies, 30 recursion replies sent, 3 replies dropped, 0 states jostled out
```

Unbound stats found:
```
total.requestlist.current.user=4294967295
```
**Note:**
If performs `flush_requestlist`, unbound will back to normal again.
If disable `serve-expired-client-timeout`, counting seems fine.

### To reproduce the problem

1. I'm using the following setting:
```
server:
    cache-min-ttl: 60
    infra-host-ttl: 600
    prefetch: yes
    serve-expired: yes
    serve-expired-ttl: 600
    serve-expired-ttl-reset: no
    serve-expired-reply-ttl: 30
    serve-expired-client-timeout: 1800
```
2. Test with consistently `dig youtube.com` in every N interval.
3. Firewall youtube's NS after first `dig`:
```
for i in {1..4}; do sudo iptables -I INPUT -j DROP -s ns$i.google.com
```
4. When youtube TTL 300 expired, TTL 30 (from `serve-expired-reply-ttl`) start to be observed
5. Leave it run for longer time, `dig` will no longer work (problem reproduced)

Tracking reply counter change in log and stats (as described above) would help you know better when it will start to break.
