### ISSUE TITLE
.Local Domain Support?

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#288]
Many years ago, Microsoft encouraged the use of .local for Active Directory domains -- AD domains can't be renamed with Exchange in-place.

While I have a forward-zone in place for this domain, it doesn't resolve hostnames to an IP from a client using unbound for DNS.

The first example forwards correctly while the second does not resolve.

```
forward-zone:
	name: "example1.net."
	forward-addr: 10.10.20.14
	forward-addr: 10.10.20.8

forward-zone:
        name: "example2.local."
        forward-addr: 10.10.20.14
        forward-addr: 10.10.20.8
```

Using unbound 1.9.0.
