### ISSUE TITLE
unbound not recovering from unhealthy backend

### ISSUE THREAD

**Issue by pmazzini** [NLnetLabs/unbound#301]
With the following example config (stub zone with a set of 2 authoritative nameservers):

```
stub-zone:
    name: "foo.bar."
    stub-addr: <address a>
    stub-addr: <address b>
```
We ran the following test and saw unbound not properly recovering:

1) Make authoritative nameserver a unresponsive
2) Unbound still replies with noerror
3) Make authoritative nameserver b unresponsive
4) Unbound servfails
5) Make authoritative nameserver a responsive again
6) **Unbound continues to servfail and does not recover**
7) Make authoritative nameserver b responsive again
8) Unbound replies with noerror again

This was the case with 1.9.6.

I need to check if this behavior is still present with 1.11.0.
