### ISSUE TITLE
Memory leak on rpz zone reloads when unbound is listening on an external interface

### ISSUE THREAD

**Issue by hpkunz** [NLnetLabs/unbound#318]
Hi all,

we are using unbound 1.11.0 on debian buster. we are testing the rpz support of unbound on two machines with 32GB RAM each. we get the rpz zones (~100MB) from our nsd servers by AXFR.

in our current configuration unbound uses around 5G after starting up and loading the rpz zones. 

however, after a few hours unbound uses up the entire memory (32G) and the oom killer starts killing unbound processes.

please note: these are test machines and do not handle any requests from clients. the only thing unbound is doing is transferring and reloading the rpz zones (when it gets a notification from the nsd servers).

unbound is listening on two interfaces/IP numbers on the same network. one is the hosts IP address, the other is a floating IP.

to our total surprise (and it took quite a while to track that down because we would never have believed it) the memory leak described above does NOT happen, when unbound listens only on one interface/IP number.

this graph shows ram usage when unbound is listening on two interface:
![unbound1](https://user-images.githubusercontent.com/5338676/95376307-35e81c80-08e1-11eb-9790-246f0cffd9c3.png)

This graph shows the same time period but with unbound only listening on one interface
![unbound2](https://user-images.githubusercontent.com/5338676/95376482-734caa00-08e1-11eb-8cc2-b9d793c77af3.jpg)

the increases in RAM usage (first graph) happen when rpz zones are being transferred and reloaded. however, the increase is different, even if the same rpz zone is reloaded. 

note that the first few zone reloads are also visible in the second graph, but only much smaller. here, the increase of RAM usage on zone reloads is not noticeable after some time.

it appears that memory is leaked when reloading rpz zones, but only when unbound listens on more than one interface.

this is our unbound.conf:
```
server:
  verbosity: 3
  num-threads: 4
  port: 53
  interface: aaa.bbb.ccc.6 # <- if this line is removed, the memory leak does not happen!
  interface: aaa.bbb.ccc.3
  interface-automatic: no 
  outgoing-range: 206
  outgoing-port-permit: "32768-65535" 
  outgoing-port-avoid: "0-32767" 
  msg-cache-size: "32m" 
  msg-cache-slabs: 4
  so-rcvbuf: "1m" 
  so-sndbuf: "1m" 
  ip-transparent: no 
  ip-freebind: yes
  rrset-cache-slabs: 4
  rrset-cache-size: "64m" 
  infra-cache-slabs: 4
  access-control:  aaa.bbb.ccc.0/24 allow
  access-control:  aaa.bbb.ddd.0/24 allow
  access-control:  aaa.bbb.eee.0/24 allow
  access-control:  aaa.bbb.fff.0/24 allow
  access-control:  aaa.bbb.ggg.0/24 allow
  username: "unbound"
  directory: "/etc/unbound"
  use-syslog: yes
  log-time-ascii: no
  log-queries: no
  log-replies: no
  hide-identity: yes
  pidfile: "/run/unbound.pid"
  root-hints: "/etc/unbound/root.hints"
  module-config: "respip validator iterator"
  auto-trust-anchor-file: "/var/lib/unbound/root.key"
  trusted-keys-file: "/etc/unbound/keys.d/*.key"
  key-cache-slabs: 4
  include-toplevel: "/etc/unbound/unbound.conf.d/*.conf" # this include our rpz zones, nothing else
```
Best,
Hp
