### ISSUE TITLE
[auth-zone] soa probe ccTLD ee. fails

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#321]
unbound 1.11.0 on Linux

```
auth-zone:
  name: "ee."
  for-downstream: no
  fallback-enabled: yes
  zonefile: "/srv/unbound/zones/ee"
  master: zone.internet.ee
```
____
`unbound-control list_auth_zones | grep ee` produces

>ee.     no serial

and it would appear that the zone transfer fails, though there is nothing printed in the logs with verbosity set to 1.

whilst inspecting the SOA retrieved with `dig @zone.internet.ee ee. axfr > /tmp/zone.ee` seems to provide a serial
