### ISSUE TITLE
[bug] no fallback to ipv4 for auth-zone if node's ipv6 upstream connectivity is not available

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#35]
1.9.1 on OpenWrt 18.06 trunk
___
in case the node's ipv6 upstream connectivity/link is unavailable `unbound`'s upstream query traffic falls back to ipv4 and dns queries are resolved.

However, for some inexplicable reason that is not working for traffic specified via:

```
auth-zone:
  name: "."
  for-downstream: no
  fallback-enabled: yes
  zonefile: "/srv/unbound/zone files/root"
  master: e.root-servers.net
  master: d.root-servers.net
  master: c.root-servers.net
  master: b.root-servers.net
  master: k.root-servers.net
  master: g.root-servers.net
  master: f.root-servers.net
```

The `unbound` log is showing is the apparent attempts to contact the root zone servers via ipv6, which fails as expected in case the node's ipv6 upstream connectivity/link is unavailable, however it would be expected then to fallback to ipv4 instead, same as `unbound` is doing for upstream query traffic that is not specified in `auth-zone`:

> info: resolving f.root-servers.net. A IN
> info: resolving f.root-servers.net. AAAA IN
> info: resolving g.root-servers.net. A IN
> info: resolving g.root-servers.net. AAAA IN
> info: resolving k.root-servers.net. A IN
> info: resolving k.root-servers.net. AAAA IN
> info: resolving b.root-servers.net. A IN
> info: resolving b.root-servers.net. AAAA IN
> info: resolving c.root-servers.net. A IN
> info: resolving c.root-servers.net. AAAA IN
> info: resolving d.root-servers.net. A IN
> info: resolving d.root-servers.net. AAAA IN
> info: resolving e.root-servers.net. A IN
> info: resolving e.root-servers.net. AAAA IN
> notice: sendto failed: Permission denied
> notice: remote address is 2001:500:2f::f port 53
> notice: sendto failed: Permission denied
> notice: remote address is 2001:500:12::d0d port 53
> notice: sendto failed: Permission denied
> notice: remote address is 2001:7fd::1 port 53
> notice: sendto failed: Permission denied
> notice: remote address is 2001:500:200::b port 53
> notice: sendto failed: Permission denied
> notice: remote address is 2001:500:2::c port 53
> notice: sendto failed: Permission denied
> notice: remote address is 2001:500:2d::d port 53
> notice: sendto failed: Permission denied
> notice: remote address is 2001:500:a8::e port 53
___
It seems that in such case unbound is not attempting ipv4 connectivity and just gives up, even with global server setting `prefer-ip6: no`.
Only way to get it working appears to be setting `do-ip6: no`
