### ISSUE TITLE
unbound-control broken

### ISSUE THREAD

**Issue by dmginc** [NLnetLabs/unbound#370]
Trying to get unbound-control to work with 1.13.0 and it doesn't seem to be working.  Trying to provide it the location of the config file, as per the unbound-control documentation, does nothing other than spit out the help information again.  

```
root@cloudhole:/var/log# unbound-control -c /etc/unbound/unbound.conf.d/pi-hole.conf
Usage:	unbound-control [options] command
	Remote control utility for unbound server.
Options:
  -c file	config file, default is /usr/local/etc/unbound/unbound.conf
  -s ip[@port]	server address, if omitted config is used.
  -q		quiet (don't print anything if it works ok).
  -h		show this usage help.
Commands:
  start				start server; runs unbound(8)
  stop				stops the server
  reload			reloads the server
  				(this flushes data, stats, requestlist)
  stats				print statistics
  stats_noreset			peek at statistics
  stats_shm			print statistics using shm
  status			display status of server
  verbosity <number>		change logging detail
  log_reopen			close and open the logfile
  local_zone <name> <type>	add new local zone
  local_zone_remove <name>	remove local zone and its contents
  local_data <RR data...>	add local data, for example
				local_data www.example.com A 192.0.2.1
  local_data_remove <name>	remove local RR data from name
  local_zones, local_zones_remove, local_datas, local_datas_remove
  				same, but read list from stdin
  				(one entry per line).
  dump_cache			print cache to stdout
  load_cache			load cache from stdin
  lookup <name>			print nameservers for name
  flush <name>			flushes common types for name from cache
  				types:  A, AAAA, MX, PTR, NS,
					SOA, CNAME, DNAME, SRV, NAPTR
  flush_type <name> <type>	flush name, type from cache
  flush_zone <name>		flush everything at or under name
  				from rr and dnssec caches
  flush_bogus			flush all bogus data
  flush_negative		flush all negative data
  flush_stats 			flush statistics, make zero
  flush_requestlist 		drop queries that are worked on
  dump_requestlist		show what is worked on by first thread
  flush_infra [all | ip] 	remove ping, edns for one IP or all
  dump_infra			show ping and edns entries
  set_option opt: val		set option to value, no reload
  get_option opt		get option value
  list_stubs			list stub-zones and root hints in use
  list_forwards			list forward-zones in use
  list_insecure			list domain-insecure zones
  list_local_zones		list local-zones in use
  list_local_data		list local-data RRs in use
  insecure_add zone 		add domain-insecure zone
  insecure_remove zone		remove domain-insecure zone
  forward_add [+i] zone addr..	add forward-zone with servers
  forward_remove [+i] zone	remove forward zone
  stub_add [+ip] zone addr..	add stub-zone with servers
  stub_remove [+i] zone		remove stub zone
		+i		also do dnssec insecure point
		+p		set stub to use priming
  forward [off | addr ...]	without arg show forward setup
				or off to turn off root forwarding
				or give list of ip addresses
  ratelimit_list [+a]		list ratelimited domains
  ip_ratelimit_list [+a]	list ratelimited ip addresses
		+a		list all, also not ratelimited
  list_auth_zones		list auth zones
  auth_zone_reload zone		reload auth zone from zonefile
  auth_zone_transfer zone	transfer auth zone from master
  view_list_local_zones	view	list local-zones in view
  view_list_local_data	view	list local-data RRs in view
  view_local_zone view name type  	add local-zone in view
  view_local_zone_remove view name  	remove local-zone in view
  view_local_data view RR...		add local-data in view
  view_local_datas view 		add list of local-data to view
  					one entry per line read from stdin
  view_local_data_remove view name  	remove local-data in view
  view_local_datas_remove view 		remove list of local-data from view
  					one entry per line read from stdin
Version 1.13.0
BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
root@cloudhole:/var/log# unbound-control reload
[1607570876] unbound-control[1206:0] warning: control-enable is 'no' in the config file.
[1607570876] unbound-control[1206:0] fatal error: could not send: Connection reset by peer
```

**Comment by dmginc** [comment]
Contents of /etc/unbound/unbound.conf.d/pi-hole.conf:

```
server:
    # If no logfile is specified, syslog is used
    # logfile: "/var/log/unbound/unbound.log"
    verbosity: 0

    interface: 127.0.0.1
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: no

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: no

    # Use this only when you downloaded the list of primary root servers!
    # If you use the default dns-root-data package, unbound will find it automatically
    #root-hints: "/var/lib/unbound/root.hints"

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    harden-dnssec-stripped: yes

    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size.
    # Suggested by the unbound man page to reduce fragmentation reassembly problems
    edns-buffer-size: 1472

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    prefetch: yes

    # One thread should be sufficient, can be increased on beefy machines. In reality for most users running on small networks or on a single machine, it should be unnecessary to seek performance enhancement by increasing num-threads above 1.
    num-threads: 1

    # Ensure kernel buffer is large enough to not lose messages in traffic spikes
    so-rcvbuf: 1m

    # Ensure privacy of local IP ranges
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10

# Remote control config section.
remote-control:
    control-enable: yes
```
