### ISSUE TITLE
Version check, reverse lookup oddity

### ISSUE THREAD

**Issue by aram535** [NLnetLabs/unbound#374]
I'm using v1.9.0 (that's what's available on ARM Debian at the moment [raspian]). 
unbound-check reports no errors

I set up a local-zone.conf file and it contains: 

main.conf:
```
server:
    logfile: "/var/log/unbound/unbound.log"
    verbosity: 0
    interface: 127.0.0.1
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes
    do-ip6: no
    prefer-ip6: no
    harden-glue: yes
    harden-dnssec-stripped: yes
    use-caps-for-id: no
    edns-buffer-size: 1472
    prefetch: yes
    num-threads: 1
    so-rcvbuf: 1m
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10
```

local-zone.conf:
```server: 
    local-zone: "168.192.in-addr.arpa." nodefault
    domain-insecure: "*"
    local-zone: "example.com." static 
    local-data: "example.com. 10800 IN NS localhost."
    local-data: "example.com. 10800 IN SOA localhost. nobody.invalid. 1 3600 1200 604800 10800"
    local-data: "test.example.com. IN A 192.168.1.10"
    local-data-ptr: "192.168.1.10 test.example.com"
```

Looking up a normal entry
```
# dig +noall +answer @127.0.0.1 -p 5335 test.example.com
test.example.com.    3600    IN      A       192.168.1.10
```
When looking up the reverse:

```
# dig +noall +answer @127.0.0.1 -p 5335 192.168.1.10
# dig +noall +answer @127.0.0.1 -p 5335 10.1.168.192.in-addr.arpa
# dig -x  ... 192.168.1.10 
```

all get forwarded to the root servers.

Is this something that was fixed/changed since 1.9+?
