### ISSUE TITLE
SIGSEGV on FreeBSD with version 1.13.0

### ISSUE THREAD

**Issue by kapfenho** [NLnetLabs/unbound#376]
With version 1.13.0 I got a segmentation violation (sorry, no core file). That's the first time, after years of stability.

Last messages:
```
Dec 14 01:03:59 <daemon.notice> homer unbound[72482]: [72482:0] notice: sendto failed: Permission denied  
Dec 14 01:03:59 <kern.info> homer kernel: pid 72482 (unbound), jid 0, uid 59: exited on signal 11  
```

System:
```
FreeBSD homer 12.2-RELEASE-p1 FreeBSD 12.2-RELEASE-p1 GENERIC  amd64
```

Unbound config (using IPv4 & IPv6):
```
server:
        verbosity: 1
        statistics-interval: 3600
        interface: ::1
        interface: ...
        interface-automatic: yes
        outgoing-interface: ...
        access-control: ... allow
        root-hints: "/usr/local/etc/unbound/root.hints"
        hide-identity: yes
        hide-version: yes
        harden-algo-downgrade: yes
        auto-trust-anchor-file: "/usr/local/etc/unbound/root.key"
remote-control:
        control-enable: yes
        control-interface: 127.0.0.1
```
