### ISSUE TITLE
Configuring unbound to do DoH with nghttp2 

### ISSUE THREAD

**Issue by JoelPCaetano97** [NLnetLabs/unbound#445]
Hello, I'm kinda new to this DNS world and I'm trying to install an unbound server to do DoH resolutions for a project.
The unbound server is configured and is running fine to do normal resolutions and resolutions through TLS.
When I added my configuration for the HTTPS I get the following message in the logs : 

``` [1616147267] unbound[2315:0] warning: Unbound is not compiled with nghttp2. This is required to use DNS-over-HTTPS. ```

Here is my configuration of the unbound.conf

``` interface: 0.0.0.0@853
    interface: ::0@853
    ssl-port: 853
    ssl-service-key: "/etc/unbound/privatekeyfile.key"
    ssl-service-pem: "/etc/unbound/publiccertfile.pem"

   interface: 0.0.0.0@443
   interface: ::0@443
   tls-service-key: "/etc/unbound/privatekeyfile.key"
   tls-service-pem: "/etc/unbound/publiccertfile.pem"
```

Is there a way to add the library nghttp on top of my unbound installation, or do I need to reinstall everything while compiling the library libnghttp2. 

Thank you in advance !

**Comment by wcawijngaards** [comment]
The http2 is enabled by compiling unbound with it, use `./configure --with-libnghttp2` with the nghttp2 devel package installed.

So, you have to reinstall the unbound binary while compiling it with the option to use libnghttp2.

**Comment by JoelPCaetano97** [comment]
First off all thank you for your response. 

Is it safe to reinstall in the same server, or should I just install in a new server ? 
I'm using LXC containers so reinstalling a brand new server whould be fast !

Thank you in advance.

**Comment by wcawijngaards** [comment]
I do not see any issues with either course of action.  The binary would be different, but that means it links with the installed libnghttp2 library, and that would not change anything else.

Make sure to not overwrite your unbound.conf; `make install` does not overwrite if the file already exists.  But I do not know what install method you use.

**Comment by JoelPCaetano97** [comment]
Thank you very much for you advice I'll give it a try !
For the installation I just installed the unbound from the apt repository like so : 
`apt-get install -y unbound dnsutils unbound-host dnssec-trigger dns-root-data`

**Comment by wcawijngaards** [comment]
You would need to change the unbound package on the repository, to use nghttp2.  Or you can install unbound yourself; after compiling it yourself have it install in /usr/local (the install prefix it uses by default), that could be a method to have your own unbound alongside the package repository provided one.

**Comment by JoelPCaetano97** [comment]
Sorry for the delayed message, but I downloaded the debian packages and compiled with the nghttp2 and installed it succesfully.
Thank you very much for the help.
Do you know any basic clients to test the DNS over HTTPS part of my unbound server ? I kinda hit a dead end in this regard !
Thank you in advance !

**Comment by wcawijngaards** [comment]
Unbound has a test client, it is part of the test code in the source repo. After configure and make, `make dohclient`. This creates the `./dohclient` test program. It can make a DNS-over-HTTPS test connection and print the output. And then you can use it like `./dohclient -s 127.0.0.1 -p 443 www.nlnetlabs.nl A IN` and that prints a lookup for that domain name.

**Comment by JoelPCaetano97** [comment]
Hello again, thank you very much, you have been a big help, everything works perfectly ! 
Have a good day :)

**Comment by seandelaney** [comment]
@JoelPCaetano97 

> Sorry for the delayed message, but I downloaded the debian packages and compiled with the nghttp2 and installed it succesfully.

Can you share the steps please?

I originally had unbound installed from running with Pi-hole using `apt-get install unbound` but a little unsure what to change to get DoH support?

**Comment by JoelPCaetano97** [comment]
@seandelaney
> @JoelPCaetano97
> 
> > Sorry for the delayed message, but I downloaded the debian packages and compiled with the nghttp2 and installed it succesfully
> 
> Can you share the steps please?
> 
> I originally had unbound installed from running with Pi-hole using `apt-get install unbound` but a little unsure what to change to get DoH support?

Of course
I started by installing the following packages as I found they are needed to compile with the DoH: 
- libssl-dev
- libexpat1-dev
- libnghttp2-dev

I then modified the sources for the APT ( I did this installation on a Debian Bullseye server) and did an update : 

``` 
sudo nano /etc/apt/sources.list
```
```
cat /etc/apt/sources.list
# Generated by distrobuilder
deb http://deb.debian.org/debian bullseye main
deb-src http://deb.debian.org/debian bullseye main
```
```
sudo apt update
```

I downloaded all the dependencies for Unbound and modified the build rules file to include the nghttp2 library

```
 root@DoHServer:~/build# apt-get build-dep unbound
```

```
root@DoHServer:~/build# apt-get source unbound
root@DoHServer:~/build# ls -l
total 5871
drwxr-xr-x 29 root root 50 Mar 26 12:21 unbound-1.13.1
-rw-r--r-- 1 root root 20428 Feb 9 23:18 unbound_1.13.1-1.debian.tar.xz
-rw-r--r-- 1 root root 3011 Feb 9 23:18 unbound_1.13.1-1.dsc
-rw-r--r-- 1 root root 5976957 Feb 9 23:18 unbound_1.13.1.orig.tar.gz
-rw-r--r-- 1 root root 833 Feb 9 23:18 unbound_1.13.1.orig.tar.gz.asc
root@DoHServer:~/build# cd unbound-1.13.1/
root@DoHServer:~/build/unbound-1.13.1#
```

I then added the following line for the first and second build  `--with-libnghttp2 \` 

```
root@DoHServer:~/build/unbound-1.13.1# nano debian/rules
```
```
...
# first build -- build unbound daemon
        PYTHON_VERSION="$(shell py3versions -vd)" \
        CFLAGS="$(CFLAGS)" CPPFLAGS="$(CPPFLAGS)" LDFLAGS="-Wl,--as-needed $(LDFLAGS)" \
                dh_auto_configure -- \
                --disable-rpath \
                --with-pidfile=/run/unbound.pid \
                --with-rootkey-file=/var/lib/unbound/root.key \
                --with-libevent \
                --with-libnghttp2 \
                --with-pythonmodule \
                --enable-subnet \
                --enable-dnstap \
                --enable-systemd \
                --with-chroot-dir="" \
                --with-dnstap-socket-path=/run/dnstap.sock \
                --libdir=/usr/lib \
                $(CONFIGURE_ARGS)
        $(MAKE)
        $(MAKE) install DESTDIR="$(CURDIR)/debian/tmp"
        $(MAKE) clean
endif

        # second build -- build libunbound only, against nettle
        CFLAGS="$(CFLAGS)" CPPFLAGS="$(CPPFLAGS)" LDFLAGS="-Wl,--as-needed $(LDFLAGS)" \
                dh_auto_configure -- \
                --disable-rpath \
                --with-libunbound-only \
                --with-nettle \
                --with-rootkey-file=/var/lib/unbound/root.key \
                --with-libevent \
                --with-libnghttp2 \
                --without-pythonmodule \
                --without-pyunbound \
                --enable-event-api \
                $(CONFIGURE_ARGS)
        $(MAKE)
        $(MAKE) install DESTDIR="$(CURDIR)/debian/tmp-lib"
        install -D -m 0644 contrib/libunbound.pc \
                $(CURDIR)/debian/libunbound-dev/usr/lib/$(DEB_HOST_MULTIARCH)/pkgconfig/libunbound.pc
        $(MAKE) clean
...
```
I then launch the compilation of unbound with the library

```
root@DoHServer:~/build/unbound-1.13.1# dpkg-buildpackage -uc -us -b
root@DoHServer:~/build# ls -l
total 15555
-rw-r--r--  1 root root  588436 Mar 26 12:30 libunbound-dev_1.13.1-1_amd64.deb
-rw-r--r--  1 root root 1434980 Mar 26 12:30 libunbound8-dbgsym_1.13.1-1_amd64.deb
-rw-r--r--  1 root root  509548 Mar 26 12:30 libunbound8_1.13.1-1_amd64.deb
-rw-r--r--  1 root root  163808 Mar 26 12:30 python3-unbound-dbgsym_1.13.1-1_amd64.deb
-rw-r--r--  1 root root  188884 Mar 26 12:30 python3-unbound_1.13.1-1_amd64.deb
drwxr-xr-x 29 root root      55 Mar 26 12:30 unbound-1.13.1
-rw-r--r--  1 root root   72628 Mar 26 12:30 unbound-anchor-dbgsym_1.13.1-1_amd64.deb
-rw-r--r--  1 root root  168844 Mar 26 12:30 unbound-anchor_1.13.1-1_amd64.deb
-rw-r--r--  1 root root 5536332 Mar 26 12:30 unbound-dbgsym_1.13.1-1_amd64.deb
-rw-r--r--  1 root root  127336 Mar 26 12:30 unbound-host-dbgsym_1.13.1-1_amd64.deb
-rw-r--r--  1 root root  184844 Mar 26 12:30 unbound-host_1.13.1-1_amd64.deb
-rw-r--r--  1 root root   20428 Feb  9 23:18 unbound_1.13.1-1.debian.tar.xz
-rw-r--r--  1 root root    3011 Feb  9 23:18 unbound_1.13.1-1.dsc
-rw-r--r--  1 root root    9160 Mar 26 12:30 unbound_1.13.1-1_amd64.buildinfo
-rw-r--r--  1 root root    4590 Mar 26 12:30 unbound_1.13.1-1_amd64.changes
-rw-r--r--  1 root root  874696 Mar 26 12:30 unbound_1.13.1-1_amd64.deb
-rw-r--r--  1 root root 5976957 Feb  9 23:18 unbound_1.13.1.orig.tar.gz
-rw-r--r--  1 root root     833 Feb  9 23:18 unbound_1.13.1.orig.tar.gz.asc
```

And installed the packages needed once the compilation was done 

```
root@DoHServer:~/build# dpkg -i unbound_1.13.1-1_amd64.deb
root@DoHServer:~/build# dpkg -i unbound-anchor_1.13.1-1_amd64.deb
root@DoHServer:~/build# dpkg -i unbound-host_1.13.1-1_amd64.deb
root@DoHServer:~/build# dpkg -i libunbound8_1.13.1-1_amd64.deb
```

Finally a little restart of the service 

```
root@DoHServer:~/build#  service unbound restart
```

And that was what I did, I hope that it helps you :)

**Comment by seandelaney** [comment]
Wow, thank you. I'll will try and follow your steps.

**Comment by AlexanderBand** [comment]
@JoelPCaetano97 Thanks a lot, we'll try to roll this into the [official documentation](https://unbound.docs.nlnetlabs.nl/en/latest/topics/privacy/dns-over-https.html). Or, if you feel comfortable with reStructuredText and you're willing to [submit a PR](https://github.com/NLnetLabs/unbound-manual/blob/master/source/topics/privacy/dns-over-https.rst), that would be epic. :)

**Comment by seandelaney** [comment]
@JoelPCaetano97 

I'm doing this on a Raspberry Pi with Pi-hole... so I can replace http://deb.debian.org/debian with http://raspbian.raspberrypi.org/raspbian right?

**Comment by seandelaney** [comment]
So some good news.... I was able to successfully build/compile Unbound with DoH using the instructions above and install the package on my Raspberry Pi with a few tweaks:

As mentioned above, I replaced `http://deb.debian.org/debian` with `http://raspbian.raspberrypi.org/raspbian` in `/etc/apt/sources.list`

After running `dpkg-buildpackage -uc -us -b`, which took about ~10 mins, I was ready to install the packages.

However, instead of `unbound_1.13.1-1_amd64.deb` I had to run `unbound_1.13.1-1_amdhf.deb` for a Raspberry Pi. 

The order also matters:

```
dpkg -i libunbound8_1.13.1-1_amdhf.deb
dpkg -i unbound-host_1.13.1-1_amdhf.deb
dpkg -i unbound-anchor_1.13.1-1_amdhf.deb
dpkg -i unbound_1.13.1-1_amdhf.deb
```

I can run commands such as these below, which return the expected results so I know it is working.

```
dig sigfail.verteiltesysteme.net @127.0.0.1 -p 443
dig sigok.verteiltesysteme.net @127.0.0.1 -p 443
dig rte.ie @127.0.0.1 -p 443
```

However, if I try pointing my Pi-hole DNS at: 127.0.0.1#443, my DNS responses come back as "N/A" and I can't get any website to load. E.g:

```
This site can’t be reached stackoverflow.com’s server IP address could not be found.
Try:

Checking the proxy, firewall and DNS configuration
DNS_PROBE_FINISHED_BAD_CONFIG
```

I've also tried with DNSSEC enabled and disabled. Neither makes a difference.

If I switch Unbound back to normal installation, running on port 5353 for example, DNS responses come back as expected and websites load fine again.

Not sure if its a Pi-hole configuration issue or Unbound configuration issue.

Here is my Unbound config at `/etc/unbound/unbound.d/pi-hole.conf`

```
server:
    # If no logfile is specified, syslog is used
    # logfile: "/var/log/unbound/unbound.log"
    verbosity: 0

    interface: 127.0.0.1
    port: 443

    tls-service-key: "/etc/lighttpd/ssl/localhost+2-key.pem"
    tls-service-pem: "/etc/lighttpd/ssl/localhost+2.pem"

    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: no

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: no

    # Use this only when you downloaded the list of primary root servers!
    # If you use the default dns-root-data package, unbound will find it automatically
    #root-hints: "/var/lib/unbound/root.hints"

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    harden-dnssec-stripped: yes

    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size.
    # IP fragmentation is unreliable on the Internet today, and can cause
    # transmission failures when large DNS messages are sent via UDP. Even
    # when fragmentation does work, it may not be secure; it is theoretically
    # possible to spoof parts of a fragmented DNS message, without easy
    # detection at the receiving end. Recently, there was an excellent study
    # >>> Defragmenting DNS - Determining the optimal maximum UDP response size for DNS <<<
    # by Axel Koolhaas, and Tjeerd Slokker (https://indico.dns-oarc.net/event/36/contributions/776/)
    # in collaboration with NLnet Labs explored DNS using real world data from the
    # the RIPE Atlas probes and the researchers suggested different values for
    # IPv4 and IPv6 and in different scenarios. They advise that servers should
    # be configured to limit DNS messages sent over UDP to a size that will not
    # trigger fragmentation on typical network links. DNS servers can switch
    # from UDP to TCP when a DNS response is too big to fit in this limited
    # buffer size. This value has also been suggested in DNS Flag Day 2020.
    edns-buffer-size: 1232

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    prefetch: yes

    # One thread should be sufficient, can be increased on beefy machines. In reality for most users running on small networks or on a single machine, it should be unnecessary>
    num-threads: 1

    # Ensure kernel buffer is large enough to not lose messages in traffic spikes
    so-rcvbuf: 1m

    # Ensure privacy of local IP ranges
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10
 
```

What are your thoughts? Does that configuration file look okay?

My Unbound-ResolvConf is unchanged at `/etc/resolv.conf`:

```
# Generated by resolvconf
nameserver 127.0.0.1
```
