### ISSUE TITLE
No response to DoH request

### ISSUE THREAD

**Issue by nikonakoneko** [NLnetLabs/unbound#453]
When I try to make a DoH request the server doesn't reply. In the logs I just have that:

```
[1616617935] unbound[22621:0] debug: comm point start listening 71 (30000 msec)
[1616617935] unbound[22621:0] debug: startlistening 71 mode r
[1616617935] unbound[22621:0] debug: SSL connection ip4 127.0.0.1 port 52306 (len 16)
[1616617935] unbound[22621:0] debug: comm_point_close of 71: event_del
[1616617935] unbound[22621:0] debug: close fd 71
```

I have the following configuration:

```
server:
        verbosity: 1
        num-threads: 4
        interface: 0.0.0.0
        interface: ::
        interface: 0.0.0.0@443
        interface: ::@443
        interface: 0.0.0.0@853
        interface: ::@853
        outgoing-range: 512
        access-control: 0.0.0.0/0 allow
        access-control: ::/0 allow
        logfile: ""
        use-syslog: no
        auto-trust-anchor-file: "/etc/dnssec/root-anchors.txt"
        tls-service-key: /etc/unbound/unbound_server.key
        tls-service-pem: /etc/unbound/unbound_server.pem
        tls-port: 853
        https-port: 443
python:
dynlib:
remote-control:
```
