### ISSUE TITLE
Garbage CNAME when using python module

### ISSUE THREAD

**Issue by justinschw** [NLnetLabs/unbound#490]
**Describe the bug**
I have unbound 1.13.1 compiled for python support.
I wrote a python module for storing DNS entries in reverse so that a proxy can use them later. The parsing happens under the MODULE_EVENT_MODDONE section, when qstate.return_msg is set.

I have an algorithm for parsing A, AAAA and CNAME entries. For the most part, they work perfectly. But I have found one particular domain that was causing an exception to be thrown:
```
ocsp.pki.goog
```
If you do a dig on this domain, you will get exactly two records:

- CNAME: ocsp.pki.goog => pki-goog.l.google.com
- A: pki-goog.l.google.com => 172.217.1.227

To debug further, I am just dumping all of the contents of the data that is passed in. What I am seeing is that the CNAME and A are parsed OK, but for some reason there is another answer parsed in between that looks like random garbage. I can see part of what kind of looks like a record wedged in there, but it is totally out of place.

I will leave my code in a comment below, with a ton of debug prints and the redis writes commented out. I will also leave the data being dumped.

**To reproduce**
1. Compile unbound 1.13.1 with python support (./configure --with-pyunbound --with-libevent --with-pythonmodule --prefix=/opt)
2. Use the following unbound.conf:
```
# Example configuration file for log.py
server:
        verbosity: 1
        interface: 0.0.0.0
        do-daemonize: no
        access-control: 0.0.0.0/0 allow
        chroot: ""
        username: ""
        directory: ""
        logfile: ""
        pidfile: "unbound.pid"
        module-config: "validator python iterator"

# Python config section
python:
        # Script file to load
        python-script: "/opt/etc/unbound/reverse.py"
```
3. Use my reverse.py (will include in a comment below)
4. Run unbound
5. Run "dig ocsp.pki.goog" against unbound
6. Check unbound output logs

**Expected behavior**
Unbound should only process the two records mentioned in the description. The records should be valid and parseable.

**System:**
 - Unbound version: 1.13.1
 - OS: Debian Linux
 - `unbound -V` output:
```
Version 1.13.1

Configure line: --with-pyunbound --with-libevent --with-pythonmodule --prefix=/opt
Linked libs: libevent 2.1.11-stable (it uses epoll), OpenSSL 1.1.1g  21 Apr 2020
Linked modules: dns64 python respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Additional information**
If it helps, here is a link to my dockerfile. You will have to replace reverse.py with the one I am supplying here.

https://github.com/justinschw/unbound-reversecache
