### ISSUE TITLE
RRsets with > 4k local-data records returning no answer

### ISSUE THREAD

**Issue by irlevesque** [NLnetLabs/unbound#505]
## Summary

We leverage local-data to propagate DNS records that are created from our canonical service discovery API. During periods of large scaling events, we have eclipsed the 64Kb maximum as documented by `msg-buffer-size`. Our expectation in this scenario is that Unbound should return a truncated list of results, but our observation is that it returns zero.

In my review of the [RFC 2181, I see](https://datatracker.ietf.org/doc/html/rfc2181#section-9):

> Where TC is set, the partial RRSet that would not completely fit may be left in the response.

So I wonder if it was an intentional choice or a bug.

### local-data include files

```bash
for s in $(seq -w 90 99); do 
  echo "server:" > local-zone.conf.40${s}
  for i in $(prips 10.1.0.0/20 | head -40${s}); do
    echo "local-data: 'example.service. 30 IN A $ip'"
  done >> local-zone.conf.40${s}
done
```

### unbound.conf

```
include: "/opt/unbound/local-zone.conf"

server:
  verbosity: 1
  interface: 0.0.0.0@53
  access-control: 0.0.0.0/0 allow
  domain-insecure: service
  local-zone: "service." static
  local-data: "service. 30 IN SOA ns.service. hostmaster.service. 1 60 60 3600 3"
  local-data: '_static.service. IN TXT "yes"'
remote-control:
  control-enable: yes
  control-port: 8954
```

### Queries

```
for s in $(seq -w 90 99); do 
  rm -f local-zone.conf
  ln -s local-zone.conf.40${s} local-zone.conf
  unbound-control -c unbound.conf reload
  res=$(dig @127.0.0.1 example.service. +noanswer 2>&1)
  numres=$(echo "$res" | grep ANSWER | sed 's/.*ANSWER: \([0-9]*\).*/\1/')
  size=$(echo "$res" | grep 'MSG SIZE' | sed 's/.*rcvd: \(.*\)/\1/')
  echo "40${s} records: ${numres} results, ${size} bytes"
  sleep .5
done
```
### Output

```
ok
4090 records: 4090 results, 65512 bytes
ok
4091 records: 4091 results, 65528 bytes
ok
4092 records: 0 results, 72 bytes
ok
4093 records: 0 results, 72 bytes
ok
```

**System:**
 - Unbound version: 1.9.4, 1.11.3
 - OS: linux
