### ISSUE TITLE
Unbound is very slow to start on Fedora

### ISSUE THREAD

**Issue by birdie-github** [NLnetLabs/unbound#509]
Takes 18 seconds to start which I believe is just inexcusable.

Here's my configuration (/etc/unbound/conf.d/custom.conf):
```
server:
  tls-cert-bundle: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
  do-ip6: no

  # file to read root hints from.
  # get one from https://www.internic.net/domain/named.cache
  root-hints: /etc/unbound/root.hints

forward-zone:
  name: "."
  forward-tls-upstream: yes

  forward-addr: 1.1.1.1@853#cloudflare-dns.com
  forward-addr: 9.9.9.9@853#dns.quad9.net
```

Everything else is **by default**. Fedora doesn't apply any unusual patches to unbound:  https://src.fedoraproject.org/rpms/unbound/tree/f33

resolved from systemd using the same configuration launched near instantly. I have no issues with connectivity.

Using `unbound-1.13.1-1.fc33.x86_64`
