### ISSUE TITLE
Logics error in zonemd-reject-absence: yes

### ISSUE THREAD

**Issue by bleve** [NLnetLabs/unbound#557]
Config like this:

```
auth-zone:
        name: "internal.example.com"
        fallback-enabled: no
        for-downstream: no
        for-upstream: yes
        primary: 172.23.80.4
        zonefile: /var/lib/unbound/internal.example.com.zone
        zonemd-check: yes
        zonemd-reject-absence: yes

```
Fail to do initial zonetransfer because there is no zone so unobund rejects it because ZONEMD is not there. Zonetransfer should happen BEFORE  zonemd check when there is no local zonefile yet.

unbound[12193]: [12193:0] warning: auth zone internal.example.com.: ZONEMD verification failed: ZONEMD absent and that is not allowed by config

Now check happens before initial zonexfer and zonemd-reject-abssence: no is required to get zonefile in first time. After that it can be enabled.
