### ISSUE TITLE
[FR] Support for RFC8375 (home.arpa.)

### ISSUE THREAD

**Issue by lifepillar** [NLnetLabs/unbound#560]
This is more a question than a feature request. Is it correct that Unbound does not implement anything related to RFC8375? For instance, RFC8375 prescribes that queries for `...home.arpa.` must not be forwarded recursively. Does Unbound do that?

If my home network uses `home.arpa`, should I just treat it as any other domain, as far as Unbound is concerned?

**Comment by AlexanderBand** [comment]
RFC8375 was recently implemented, in commit https://github.com/NLnetLabs/unbound/commit/89510f4a0cb60e0f7d1388e497f1b5feb0464d04.

**Comment by rwjack** [comment]
Grave digging a bit, but just in case it helps someone. After updating Debian `11 -> 12`, my unbound package updated `1.13.1 -> 1.17.1`, which caused the `home.arpa` forward zone to break.

```
forward-zone:
    name: "home.arpa."
    forward-addr: internal.dns.server.ipv4

server:
    domain-insecure: "home.arpa"
    private-domain: "home.arpa"
```

Adding: `local-zone: "home.arpa." nodefault` under private-domain fixed my issues.
