### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by SP-937-215** [NLnetLabs/unbound#561]
Hello,

**Describe the bug**
I am installing Unbound on a VPS as recursive/caching/validating DNS server for my private usage. I want to leverage DoT for downstream queries (from mobile phones). To do this, I am using a private key and certificate from Let's Encrypt (staging env.) managed by Caddy server: after generation of the key and certificate, I simply copy/paste them in /etc/unbound. In this test configuration and to ease the setup, Caddy does not act as a reverse proxy, Unbound listens directly on 0.0.0.0:853.

I get the following error:
`error: ssl handshake failed crypto error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca`

**To reproduce**
1. Spin-up a Caddy Docker image and configure it for a registered domain name 
2. Get the private key and certificate from the /data folder and copy them in /etc/unbound. Adjust unbound config accordingly
3. Start Unbound
4. In an Android phone, setup the private DNS to initiate the connection

**Expected behavior**
Successful TLS handshake

**System:**
 - Unbound version: 1.13.2
 - OS: Arch Linux
 - `unbound -V` output:

```
Version 1.13.2

Configure line: --prefix=/usr --sysconfdir=/etc --localstatedir=/var --sbindir=/usr/bin --disable-rpath --enable-dnscrypt --enable-dnstap --enable-pie --enable-relro-now --enable-subnet --enable-systemd --enable-tfo-client --enable-tfo-server --enable-cachedb --with-libhiredis --with-conf-file=/etc/unbound/unbound.conf --with-pidfile=/run/unbound.pid --with-rootkey-file=/etc/trusted-key.key --with-libevent --with-libnghttp2 --with-pyunbound
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 1.1.1l  24 Aug 2021
Linked modules: dns64 cachedb subnetcache respip validator iterator
DNSCrypt feature available
TCP Fastopen feature available
```

**Additional information**
- Unbound.conf:
```
server:
        verbosity: 5
        access-control: 0.0.0.0/0 allow
        access-control: ::/0 allow
        aggressive-nsec: yes
        trust-anchor-file: trusted-key.key
        cache-max-ttl: 14400
        cache-min-ttl: 1200
        chroot: "/etc/unbound"
        directory: "/etc/unbound"
        do-ip4: yes
        do-ip6: yes
        do-tcp: yes
        hide-identity: yes
        hide-version: yes
        interface: 0.0.0.0@53
        interface: ::@53
        interface: 0.0.0.0@853
        interface: ::@853
        port: 53
        prefetch: yes
        rrset-roundrobin: yes
        so-reuseport: yes
        tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"
        tls-service-key: "dns.domain.com.key"
        tls-service-pem: "dns.domain.com.pem"
        tls-port: 853
        tls-ciphersuites: "TLS_AES_128_GCM_SHA256:TLS_AES_128_CCM_8_SHA256:TLS_AES_128_CCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256"
        use-caps-for-id: yes
        username: unbound
        root-hints: "root.hints"
```

**Additional question**

What are the requirements for the certificate and the private key? Is it:

- certificate.pem = SSL certificate + Intermediate certificate + Root certificate
- privkey.key = Private key + SSL certificate + Intermediate certificate + Root certificate

Or something else?

Thank you!
