### ISSUE TITLE
Documenation clarification on RTT band

### ISSUE THREAD

**Issue by balaziks** [NLnetLabs/unbound#567]
[Unbound Timeout Information](https://nlnetlabs.nl/documentation/unbound/info-timeout/) in the documentation says that:
> The fastest server (randomly picked within a so-called RTT band of 400 msec) is selected when a query has to be sent out.

Which led me to believe that this 400 ms band is static meaning that the server is selected uniformly from those believed to have RTT of 400 ms and lower.

From the [code](https://github.com/NLnetLabs/unbound/blob/829f3c932e325df537adf3df9deae664ab5e321d/iterator/iter_utils.c#L553) this is clearly not the case and the 400 ms is used as the RTT band only at first. This is confirmed by measurements I did such as this [one](https://user-images.githubusercontent.com/3730829/140890947-2a8971ee-3119-4a31-97cd-460b2ab5e750.png).

Can you please explain (in this issue or maybe even on the mentioned docs page) how the band is computed later once there are some data in the infra cache?

Thanks!

**Comment by gthess** [comment]
Hi Stepan,
Thanks for checking and reaching out to us!
Indeed, the RTT band is later used as the RTT difference between the fastest server and the rest.
With configuration options like `fast-server-permil:` and `fast-server-num:` you can further influence the 400 ms value (it can only go lower), but I don't think you have any of that because you are using the default config.

What maybe happens in your measurements is that the other two servers are not even considered for selection. The following function documents which cases are those: https://github.com/NLnetLabs/unbound/blob/829f3c932e325df537adf3df9deae664ab5e321d/iterator/iter_utils.c#L228
You can also get infra cache numbers from Unbound itself with `unbound-control dump_infra` and the numbers there may hint to one of the cases.

It could also be the case that there is bug lurking somewhere so let me know how it goes.

**Comment by balaziks** [comment]
After the run of 10k queries to a zone with simulated RTTs like this:

```
194.0.14.1	211.27ms
2001:678:10::1	19.5ms
194.0.13.1	60.43ms
193.29.206.1	152.59ms
194.0.12.1	77.41ms
2001:678:11::1  237.86ms
2001:678:f::1	152.84ms
2001:678:1::1	178.25ms
```

output of `unbound-control dump_infra` looks like this

```
2001:678:10::1 . ttl 886 ping 19 var 3 rtt 50 rto 50 tA 0 tAAAA 0 tother 0 ednsknown 1 edns 0 delay 0 lame dnssec 0 rec 0 A 0 other 0
193.29.206.1 . ttl 886 ping 146 var 9 rtt 182 rto 182 tA 0 tAAAA 0 tother 0 ednsknown 1 edns 0 delay 0 lame dnssec 0 rec 0 A 0 other 0
2001:678:1::1 . ttl 886 ping 172 var 9 rtt 208 rto 208 tA 0 tAAAA 0 tother 0 ednsknown 1 edns 0 delay 0 lame dnssec 0 rec 0 A 0 other 0
194.0.14.1 . ttl 886 ping 206 var 8 rtt 238 rto 238 tA 0 tAAAA 0 tother 0 ednsknown 1 edns 0 delay 0 lame dnssec 0 rec 0 A 0 other 0
194.0.13.1 . ttl 886 ping 55 var 8 rtt 87 rto 87 tA 0 tAAAA 0 tother 0 ednsknown 1 edns 0 delay 0 lame dnssec 0 rec 0 A 0 other 0
194.0.12.1 . ttl 886 ping 71 var 9 rtt 107 rto 107 tA 0 tAAAA 0 tother 0 ednsknown 1 edns 0 delay 0 lame dnssec 0 rec 0 A 0 other 0
2001:678:f::1 . ttl 886 ping 149 var 6 rtt 173 rto 173 tA 0 tAAAA 0 tother 0 ednsknown 1 edns 0 delay 0 lame dnssec 0 rec 0 A 0 other 0
2001:678:11::1 . ttl 886 ping 236 var 4 rtt 252 rto 252 tA 0 tAAAA 0 tother 0 ednsknown 1 edns 0 delay 0 lame dnssec 0 rec 0 A 0 other 0
```

with the measured packet distribution looking like this

![unbound](https://user-images.githubusercontent.com/3730829/141795618-4f4dc0ca-b7fc-498a-a07f-79104397f826.png)

The `ping` estimates look apt, but reading the code of `iter_filter_unsuitable` I still can't see a reason why they are excluded from the choice.

Just for completeness sake I'm attaching the `unbound.conf` used

```
server:
    verbosity: 0
    statistics-interval: 0
    extended-statistics: yes
    interface: 1.0.0.1
    interface: 1::1
    port: 53
    outgoing-interface: 1.0.0.1
    outgoing-interface: 1::1
    do-daemonize: no
    access-control: ::0/0 allow_snoop
    access-control: 0.0.0.0/0 allow_snoop
    chroot: ""
    username: ""
    directory: ""
    log-time-ascii: yes
    log-queries: no
    target-fetch-policy: "0 0 0 0 0"
    use-caps-for-id: yes
    do-ip6: yes
    do-ip4: yes
    domain-insecure: "."
    num-threads: 1
    root-hints: "/tmp/maze-cz_zone_from_taiwan-xpyz66ve/resolver/root.hints"

remote-control:
    control-enable: yes
    control-use-cert: no
```

the full [PCAP](balazik.cz/tmp/result_unbound.pcap) of the test run (note that there are some mDNS queries used as markers of the various processes starting and stopping, you can ignore those) as well as the zone the auths are serving and root hints:

```
.			86400	IN	SOA	a.ns.nic.cz. nstld.verisign-grs.com. 2019072500 1800 900 604800 86400
*.		  3600	    IN	A   	1.1.1.1
.			518400	IN	NS	a.ns.nic.cz.
.			518400	IN	NS	b.ns.nic.cz.
.			518400	IN	NS	c.ns.nic.cz.
.			518400	IN	NS	d.ns.nic.cz.
a.ns.nic.cz. 518400	IN	A   	194.0.12.1
b.ns.nic.cz. 518400	IN	A   	194.0.13.1
c.ns.nic.cz. 518400	IN	A       194.0.14.1
d.ns.nic.cz. 518400	IN	A       193.29.206.1
a.ns.nic.cz. 518400	IN	AAAA    2001:678:f::1
b.ns.nic.cz. 518400	IN	AAAA    2001:678:10::1
c.ns.nic.cz. 518400	IN	AAAA    2001:678:11::1
d.ns.nic.cz. 518400	IN	AAAA    2001:678:1::1
```

```
.			518400	IN	NS	a.ns.nic.cz.
.			518400	IN	NS	b.ns.nic.cz.
.			518400	IN	NS	c.ns.nic.cz.
.			518400	IN	NS	d.ns.nic.cz.
a.ns.nic.cz. 518400	IN	A   	194.0.12.1
b.ns.nic.cz. 518400	IN	A   	194.0.13.1
c.ns.nic.cz. 518400	IN	A       194.0.14.1
d.ns.nic.cz. 518400	IN	A       193.29.206.1
a.ns.nic.cz. 518400	IN	AAAA    2001:678:f::1
b.ns.nic.cz. 518400	IN	AAAA    2001:678:10::1
c.ns.nic.cz. 518400	IN	AAAA    2001:678:11::1
d.ns.nic.cz. 518400	IN	AAAA    2001:678:1::1
```

The simulated client sends queries  `[0-99999]. IN A` in order.

Feel free to tell me, if you need anything else (such as a run with verbose log)!
