### ISSUE TITLE
Forward zones and recursive DNSSEC validation

### ISSUE THREAD

**Issue by maciejsszmigiero** [NLnetLabs/unbound#571]
Do forward zones do a fully local recursive DNSSEC validation or just trust the `AD` bit from the remote server?

Specifically, with a config like the one below (that unconditionally forwards all requests to an upstream server), will Unbound walk the whole path to the trust anchor and verify DNSSEC signatures there locally (like, for example, [Stubby](https://github.com/getdnsapi/stubby) does)?
Or will it just trust the answer from the remove server (like the `AD` bit)?

Example config:
```
forward-zone:
        name: "."
        forward-tls-upstream: yes
        forward-addr: 1.2.3.4@853#some-DoT-server
```
