### ISSUE TITLE
Interesting domain and unbound not able to resolve it

### ISSUE THREAD

**Issue by sevengiants** [NLnetLabs/unbound#587]
**Describe the bug**
"tmpcomic.com" is unable to be resolved, unbound error server not reachable
tried my best to look verbose log and lost myself after many iterations

**To reproduce**
maybe to do with this domain NS has multiple layers of cdn, everytime i tried at my server, always end up server not reachable

**Expected behavior**

**System:**
Version 1.13.1

Configure line: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --disable-rpath --with-pidfile=/run/unbound.pid --with-rootkey-file=/var/lib/unbound/root.key --with-libevent --with-libnghttp2 --with-pythonmodule --enable-subnet --enable-dnstap --enable-systemd --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --libdir=/usr/lib
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 1.1.1l  24 Aug 2021
Linked modules: dns64 python subnetcache respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

**Additional information**
Add any other information that you may have gathered about the issue here.

**Comment by wcawijngaards** [comment]
The domain has no records, at this time. So the resolution works fine, but the authority for the domain reports zero records for the domain. No A, AAAA or MX records.

For example `dig @129.211.176.224 +norec tmpcomic.com` shows you that the server reports no records for it.

```
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43505
;; flags: qr aa; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;tmpcomic.com.			IN	A

;; AUTHORITY SECTION:
tmpcomic.com.		180	IN	SOA	f1g1ns1.dnspod.net. freednsadmin.dnspod.com. 1629547990 3600 180 1209600 180

;; Query time: 243 msec
;; SERVER: 129.211.176.224#53(129.211.176.224)
;; WHEN: Wed Dec 15 09:42:04 CET 2021
```

This is also what unbound fetches, and thus reports no records for it. So there is no actual error, there is simply no data, called a nodata answer. So the domain exists, but has no records returned for it.

The IP address is for
```
f1g1ns2.dnspod.net.     86400   IN      A       129.211.176.224
```
because the tmpcomic.com domain has these nameservers
```
tmpcomic.com.   86400   IN      NS      f1g1ns2.dnspod.net.
tmpcomic.com.   86400   IN      NS      f1g1ns1.dnspod.net.
```

**Comment by sevengiants** [comment]
Yep these were all making sense.

If you dig from 8.8.4.4, you will see it eventually get some cdn nodes and it is a cname. Which really confuses me. How did 8.8.4.4 eventually get such results.

**Comment by wcawijngaards** [comment]
I am closing the issue. There is no question for unbound to solve here. It reports correctly what is found in the DNS. I can also not clear up your confusion, because I can only tell what Unbound is doing.

**Comment by sevengiants** [comment]
the root domain may not have details but the m.tmpcomic.com has

; <<>> DiG 9.16.1-Ubuntu <<>> m.tmpcomic.com @8.8.4.4
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15207
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;m.tmpcomic.com.                        IN      A

;; ANSWER SECTION:
m.tmpcomic.com.         600     IN      CNAME   ap.cdn.yunjiasu360.com.
ap.cdn.yunjiasu360.com. 10      IN      A       23.249.27.192
ap.cdn.yunjiasu360.com. 10      IN      A       23.249.27.177
ap.cdn.yunjiasu360.com. 10      IN      A       198.176.50.188
ap.cdn.yunjiasu360.com. 10      IN      A       198.176.56.90
ap.cdn.yunjiasu360.com. 10      IN      A       104.251.237.27

;; Query time: 50 msec
;; SERVER: 8.8.4.4#53(8.8.4.4)
;; WHEN: Wed Dec 15 10:16:21 GMT 2021
;; MSG SIZE  rcvd: 156

**Comment by wcawijngaards** [comment]
That domain, m.tmpcomic.com, seems to resolve fine with Unbound. It returns that CNAME and the list of IP addresses.

**Comment by sevengiants** [comment]
@wcawijngaards 

the previous comment was results from 8.8.4.4

```
; <<>> DiG 9.16.1-Ubuntu <<>> m.tmpcomic.com @8.8.4.4
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15207
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;m.tmpcomic.com. IN A

;; ANSWER SECTION:
m.tmpcomic.com. 600 IN CNAME ap.cdn.yunjiasu360.com.
ap.cdn.yunjiasu360.com. 10 IN A 23.249.27.192
ap.cdn.yunjiasu360.com. 10 IN A 23.249.27.177
ap.cdn.yunjiasu360.com. 10 IN A 198.176.50.188
ap.cdn.yunjiasu360.com. 10 IN A 198.176.56.90
ap.cdn.yunjiasu360.com. 10 IN A 104.251.237.27

;; Query time: 50 msec
;; SERVER: 8.8.4.4#53(8.8.4.4)
;; WHEN: Wed Dec 15 10:16:21 GMT 2021
;; MSG SIZE rcvd: 156
```

But from my own unbound

```
; <<>> DiG 9.16.15-Ubuntu <<>> m.tmpcomic.com @127.0.0.1 -p 5335
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 39
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;m.tmpcomic.com.                        IN      A

;; Query time: 0 msec
;; SERVER: 127.0.0.1#5335(127.0.0.1)
;; WHEN: Wed Dec 15 13:52:30 GMT 2021
;; MSG SIZE  rcvd: 43
```

**Comment by sevengiants** [comment]
my conf file

```
server:

    # The  verbosity  number, level 0 means no verbosity, only errors.
    # Level 1 gives operational information. Level  2  gives  detailed
    # operational  information. Level 3 gives query level information,
    # output per query.  Level 4 gives  algorithm  level  information.
    # Level 5 logs client identification for cache misses.  Default is
    # level 1.
    verbosity: 0

    interface: 127.0.0.1
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: no

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: no

    # Use this only when you downloaded the list of primary root servers!
    # Read  the  root  hints from this file. Make sure to
    # update root.hints evry 5-6 months.
    root-hints: "/var/lib/unbound/root.hints"

    # Trust glue only if it is within the servers authority
    harden-glue: yes

    # Ignore very large queries.
    harden-large-queries: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    # If you want to disable DNSSEC, set harden-dnssec stripped: no
    harden-dnssec-stripped: yes

    # Number of bytes size to advertise as the EDNS reassembly buffer
    # size. This is the value put into  datagrams over UDP towards
    # peers. The actual buffer size is determined by msg-buffer-size
    # (both for TCP and UDP).
    edns-buffer-size: 1232

    # Rotates RRSet order in response (the pseudo-random
    # number is taken from Ensure privacy of local IP
    # ranges the query ID, for speed and thread safety).
    # private-address: 192.168.0.0/16
    rrset-roundrobin: yes

    # Time to live minimum for RRsets and messages in the cache. If the minimum
    # kicks in, the data is cached for longer than the domain owner intended,
    # and thus less queries are made to look up the data. Zero makes sure the
    # data in the cache is as the domain owner intended, higher values,
    # especially more than an hour or so, can lead to trouble as the data in
    # the cache does not match up with the actual data anymore
    cache-min-ttl: 300
    cache-max-ttl: 86400

    # Have unbound attempt to serve old responses from cache with a TTL of 0 in
    # the response without waiting for the actual resolution to finish. The
    # actual resolution answer ends up in the cache later on.
    serve-expired: yes

    # Harden against algorithm downgrade when multiple algorithms are
    # advertised in the DS record.
    harden-algo-downgrade: yes

    # Ignore very small EDNS buffer sizes from queries.
    harden-short-bufsize: yes

    # Refuse id.server and hostname.bind queries
    hide-identity: yes

    # Report this identity rather than the hostname of the server.
    identity: "UnboundLocal"

    # Refuse version.server and version.bind queries
    hide-version: yes

    # Prevent the unbound server from forking into the background as a daemon
    do-daemonize: no

    # Number  of  bytes size of the aggressive negative cache.
    neg-cache-size: 4m

    # Send minimum amount of information to upstream servers to enhance privacy
    qname-minimisation: yes

    # Deny queries of type ANY with an empty response.
    # Works only on version 1.8 and above
    deny-any: yes

    # Do no insert authority/additional sections into response messages when
    # those sections are not required. This reduces response size
    # significantly, and may avoid TCP fallback for some responses. This may
    # cause a slight speedup
    minimal-responses: yes

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    # This flag updates the cached domains
    prefetch: yes

    # Fetch the DNSKEYs earlier in the validation process, when a DS record is
    # encountered. This lowers the latency of requests at the expense of little
    # more CPU usage.
    prefetch-key: yes

    # One thread should be sufficient, can be increased on beefy machines. In reality for
    # most users running on small networks or on a single machine, it should be unnecessary
    # to seek performance enhancement by increasing num-threads above 1.
    num-threads: 1

    # more cache memory. rrset-cache-size should twice what msg-cache-size is.
    msg-cache-size: 50m
    rrset-cache-size: 100m

    # Faster UDP with multithreading (only on Linux).
    so-reuseport: yes

    # Ensure kernel buffer is large enough to not lose messages in traffix spikes
    so-rcvbuf: 4m
    so-sndbuf: 4m

    # Set the total number of unwanted replies to keep track of in every thread.
    # When it reaches the threshold, a defensive action of clearing the rrset
    # and message caches is taken, hopefully flushing away any poison.
    # Unbound suggests a value of 10 million.
    unwanted-reply-threshold: 100000

    # Minimize logs
    # Do not print one line per query to the log
    log-queries: no
    #log-queries: yes
    # Do not print one line per reply to the log
    log-replies: no
    #log-replies: yes
    # Do not print log lines that say why queries return SERVFAIL to clients
    log-servfail: no
    #log-servfail: yes
    # Do not print log lines to inform about local zone actions
    log-local-actions: no
    #log-local-actions: yes
    # Do not print log lines that say why queries return SERVFAIL to clients
    logfile: /dev/null
    #logfile: /var/log/unbound.log

    #verbosity: 5

    # Ensure privacy of local IP ranges
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10

    val-permissive-mode: yes
```
