### ISSUE TITLE
logfile config option ignored

### ISSUE THREAD

**Issue by elderlabs** [NLnetLabs/unbound#592]
According to the documentation, Unbound should log to a `logfile` when specified in the config, which should then also disable logging to syslog. This is the expected behavior, however, does not seem to be the case. I've verified Unbound's user has access to the logfile, specified in the config, and verified I'm running the latest version available via Debian 11's apt repo, `1.13.1-1`, but can see no fault on my end. The config options I'm using are listed below.

```
server:
    # If no logfile is specified, syslog is used
    logfile: "/var/log/unbound/unbound.log"
    log-queries: no
    use-syslog: no
    verbosity: 3
```

Thanks.
