### ISSUE TITLE
How to set up an RPZ with a url in unbound.conf

### ISSUE THREAD

**Issue by rx570gtx1060** [NLnetLabs/unbound#594]
OS: Opensuse Tumbleweed
Version:1.14.0

The Docs and the medium page haven't helped.

The URL's l would like to use are:
rpz.oisd.nl
https://energized.pro/ultimate/formats/rpz.txt

But everytime that I try some sort of combination using the specified rpz syntax there is a syntax error reported whenever I restart Unbound.

Is anybody able to write out an rpz example that works using the URL's above?

**Comment by jpgpi250** [comment]
```
server:
module-config: "respip validator iterator"

rpz:
     name: oisd
     zonefile: zonefiles/oisd.zone
     url: https://energized.pro/ultimate/formats/rpz.txt
     rpz-action-override: nxdomain
     rpz-log: yes
     rpz-log-name: oisd
```
dig 000123456789.online

```
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 20743
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
```

unbound log:
`Dec 29 11:33:01 unbound[30003:3] info: rpz: applied [oisd] 000123456789.online. rpz-nxdomain 192.168.2.228@58877 000123456789.online. A IN`

- rpz-log-name oisd creates a comment in the logline between the [] brackets only, this to identify the rpz zonefile, when using multiple rpz entries.
- the above path (zonefiles/) is really /etc/unbound/zonefiles/, using chroot notation to make it work.

- you can have only one **modules-config** in all of the configuration files, last one will be used.
- some modules are incompatible, use unbound-checkconf to see possible incompatibilities. see also [here](https://github.com/NLnetLabs/unbound/issues/593).
- set the correct permissions for the zonefile folder, see my [manual](https://jpgpi250.github.io/piholemanual/doc/Unbound%20response%20policy%20zones.pdf) (setup rpz) for details.
