### ISSUE TITLE
More graceful forward-zone

### ISSUE THREAD

**Issue by soffchen** [NLnetLabs/unbound#62]
I have lots of forward-zones with the same multi forward-addr like this:

```
forward-zone:
  name: "zzzzaaaa.com."
  forward-addr: 119.29.29.29
  forward-addr: 114.114.114.114
  forward-addr: 223.5.5.5

forward-zone:
  name: "zzzzhong.com."
  forward-addr: 119.29.29.29
  forward-addr: 114.114.114.114
  forward-addr: 223.5.5.5

forward-zone:
  name: "zzzzmall.com."
  forward-addr: 119.29.29.29
  forward-addr: 114.114.114.114
  forward-addr: 223.5.5.5
```

Too many repeat settings make the config file large. How about this idea?

```
forward-group:
  name: "default"
  forward-addr: 119.29.29.29
  forward-addr: 114.114.114.114
  forward-addr: 223.5.5.5

forward-zone:
  name: "zzzzaaaa.com."
  group: "default"

forward-zone:
  name: "zzzzmall.com."
  group: "default"
```

or single setting with a name list

```
forward-zone:
  name-list: "filename_with_domain_list_only_forward_to_the_same_addr"
  forward-addr: 119.29.29.29
  forward-addr: 114.114.114.114
  forward-addr: 223.5.5.5
```
