### ISSUE TITLE
local root zone can't resolving some domain

### ISSUE THREAD

**Issue by ziojacky** [NLnetLabs/unbound#646]
i use unbound 1.15 made a root zone resolution server, but some domain can't resolving, main problem domain is all root-servers.net and icann with internic, but other domain can normal resolution, unbound compile with libevent, my unbound conf is :

```
server:
	verbosity: 1
	num-threads: 2
	port: 53
       interface: 127.0.0.1
	do-ip6: no
	access-control: 0.0.0.0/0 allow
	logfile: "unbound.log"
	root-hints: "root.hints"
	auto-trust-anchor-file: "root.key"

auth-zone:
    name: "."
	for-downstream: no
	for-upstream: yes
	zonefile: "root.zone"
```
