### ISSUE TITLE
[FR] Allow RFC8806 configuration using FQDN

### ISSUE THREAD

**Issue by paultheweird** [NLnetLabs/unbound#662]
**Current behavior**
When running local root (RFC8806) with this configuration:
```        
auth-zone:
        name: "."
                primary: "b.root-servers.net"
                primary: "c.root-servers.net"
                primary: "d.root-servers.net"
                primary: "f.root-servers.net"
                primary: "g.root-servers.net"
                primary: "k.root-servers.net"
                fallback-enabled: no
                for-downstream: no
                for-upstream: yes
                zonefile: "/var/unbound/db/root.zone"
```
Unbound will not use the root hints from `iterator/iter_hints.c` to resolve the names of the primaries that are configured. This presents a boot-strapping issue when first configuring unbound, or when the unbound instance loses connectivity for a prolonged period. This can of course easily be fixed with:

```
                primary: 2001:7fd::1
                primary: 193.0.14.129
```
But that risks going out of date (although for K, I'm pretty sure it'll be quite stable for the foreseeable future) An alternative is to use `fallback-enabled: yes`.

**Describe the desired feature**
The feature should be to use the hard-coded addresses from `iterator/iter_hints.c` in this case. That file gets updated with newer adresses for the root letters such that software updates will keep the user current.

**Potential use-case**
For RFC8806 users, it makes their configuration more idiomatic by simply referring to primaries by their name.
