### ISSUE TITLE
[FR] Ability to filter DNS requests for certain domains

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#669]
Dear Unbound team,

In a "split horizon" network where a high number of clients are connected to the corporate network via remote VPN during work hours and not after hours - we see a lot of DNS queries for "in-house" zones that are only available on VPN through the in-house DNSes. This accumulates wasteful traffic towards the public DNS servers (which we use as forwarders for "."). 

Would it be possible to have a function that filters (or ignores/mutes) queries for certain domain-names?

A big thanks to the crew of NLnetLabs for providing this gem of DNS service! :)

**Comment by Philip-NLnetLabs** [comment]
Hi,

The ability to filter domains is provided by the 'local-zone' configuration option. In particular, when the type is set to deny, refuse or static.

Is there anything missing from this feature that you need?

Philip

**Comment by kokial** [comment]
This feature needs compiled Unbound with respip module, add it to module-config:

`module-config: "respip validator iterator"`

Define a tag before access-control with a name:

`define-tag: "malware"`

Link tag with access-control or interface

```
access-control: 10.0.0.1/8 allow
access-control-tag: 10.0.0.1/8 "malware"
```

Create a rpz section, down in the unbound.conf

```
rpz:
  name: "localhost"
  zonefile: "/etc/unbound/unbound.rpz"
  rpz-action-override: cname
  rpz-cname-override: "---Blocked.domain---"
  rpz-signal-nxdomain-ra: no
  tags: "malware"
```

The format in the unbound.rpz file is` domain` `CNAME .`
www.example1.com CNAME .
www.eample2.org CNAME .
