### ISSUE TITLE
[FR] When forward-tls-upstream: yes, ports should default to 853

### ISSUE THREAD

**Issue by pemensik** [NLnetLabs/unbound#672]
**Current behavior**
I tried configuring DNS over TLS for use by unbound-host. But I struggled with correct configuration
I used this:
```
server:
        # Certificates used to authenticate connections made upstream.
        tls-cert-bundle: "/etc/pki/tls/certs/ca-bundle.crt"

forward-zone:
        name: "."
        forward-addr: 1.1.1.1
        forward-addr: 1.0.0.1
        forward-tls-upstream: yes
```
But it did not work.

Found out different way is needed
```
forward-zone:
        name: "."
        forward-addr: 1.1.1.1@853
        forward-addr: 1.0.0.1@853
        forward-tls-upstream: yes
```

**Describe the desired feature**

I would like just toggle forward-tls-upstream variable without explicitly changing destination ports. It should remember whether ports were explicitly given and override the default. But I would like default port 853 on DoT and 443 on DoH. I would like to just change used tls flag and do not care about manual ports. Is that possible?

I am not sure how DNS over HTTPS to upstream can be enabled. Is that even possible? Is it done just by port?

**Potential use-case**
It would be more user friendly to switch to and from DNS over TLS. Change just single variable controlling it and do not care about technical details. Of course allow still explicit port specification, which would always override the default.
