### ISSUE TITLE
allow-notify doesn't work for url on rpz zones

### ISSUE THREAD

**Issue by alisson276** [NLnetLabs/unbound#679]
**Describe the bug**
Setting a `allow-notify` setting with an IP address doesn't allow Unbound receive notifications from that IP on RPZ zones.

**To reproduce**
1. Configure a config file like this:
```
server:
    module-config: "respip validator iterator"
    directory: "/usr/local/etc/unbound"
    username: unbound
    chroot: "/usr/local/etc/unbound"
    logfile: "/usr/local/etc/unbound/logs/unbound.log"
    log-time-ascii: yes
    trust-anchor-file: "/usr/local/etc/unbound/root.key"
    verbosity: 4      # get more logging.
    interface: 0.0.0.0
    extended-statistics: yes 
    access-control: 10.0.0.0/16 allow
    private-address: 10.0.0.0/16

remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    server-key-file: "/usr/local/etc/unbound/unbound_server.key"
    server-cert-file: "/usr/local/etc/unbound/unbound_server.pem"
    control-key-file: "/usr/local/etc/unbound/unbound_control.key"
    control-cert-file: "/usr/local/etc/unbound/unbound_control.pem"

forward-zone:
  name: "."
  forward-addr: 1.1.1.1

rpz:
    name: rpz.allowed.domains
    url: "https://mytest.server.com/rpz.allowed.domains"
    rpz-log: yes
    rpz-log-name: rpz-allowed-domain
    allow-notify: 10.0.0.1

rpz:
    name: rpz.blocked.domains
    url: "https://mytest.server.com/rpz.blocked.domains"
    rpz-log: yes
    rpz-log-name: rpz-blocked-domain
    allow-notify: 10.0.0.1
```
3. Use the `https://github.com/abh/dns-notify` or other tool to call NOTIFY on the VM 10.0.0.1
```
go run dns-notify.go -domain rpz.allowed.domains 10.0.0.2:53
```
5. The server will answer `not ok (REFUSED)`

**Expected behavior**

We expected it succeed and downloaded the zone file as soon as received the NOTIFY message.

**System:**
 - Unbound version: 1.15.0
 - OS: CentOS 7
 - `unbound -V` output:
```
Version 1.15.0

Configure line:
Linked libs: mini-event internal (it uses select), OpenSSL 1.0.2k-fips  26 Jan 2017
Linked modules: dns64 respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Additional information**
I added a lot of `log_err()` to realize what happen and what I could understand is if we don't have `task_probe` (no primary zone dns servers) the `auth_master` struct (xfr->allow_notify_list) never gets values from allow-notify setting and that's why unbound refuses to receive the notify.
