### ISSUE TITLE
UDP only: connection timed out; no servers could be reached

### ISSUE THREAD

**Issue by sebolabs** [NLnetLabs/unbound#707]
**Describe the bug**
Possibly me doing something wrong, but need your help!

The issue I encountered is that unbound does not reply to queries from remote networks.
I have a local network (192.168.0.0/24) and a remote AWS network (10.0.0.0/8).
They are integrated with the use of VPN and TGW.
All traffic between both networks is allowed, netcat/telnet are happy.

From any host in the local network UDP queries work fine.
However, when I try to query `unbound` from the remote AWS network it fails with:
```
root@ip-10-0-2-6:~# dig xxx.dummy.blah @192.168.0.158

; <<>> DiG 9.18.1-1ubuntu1.1-Ubuntu <<>> xxx.dummy.blah @192.168.0.158
;; global options: +cmd
;; connection timed out; no servers could be reached
``` 
If I only add `+tcp` flag it gets a successful response.

**To reproduce**
N/A

**Expected behavior**
It should respond to UDP queries

**System:**
 - Unbound version: `1.9.4-2ubuntu1.2`
 - OS: `Linux pi 5.4.0-1065-raspi #75-Ubuntu SMP PREEMPT Fri Jun 3 14:24:57 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`
 - unbound -V: 
``` 
Version 1.9.4

Configure line: --build=aarch64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/aarch64-linux-gnu --libexecdir=${prefix}/lib/aarch64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --disable-rpath --with-pidfile=/run/unbound.pid --with-rootkey-file=/var/lib/unbound/root.key --with-libevent --with-pythonmodule --enable-subnet --enable-dnstap --enable-systemd --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --libdir=/usr/lib --disable-flto
Linked libs: libevent 2.1.11-stable (it uses epoll), OpenSSL 1.1.1f  31 Mar 2020
Linked modules: dns64 python subnetcache respip validator iterator
```

**Additional information**
My unbound.conf
```
server:
  port: 53
  interface: 0.0.0.0

  verbosity: 4

  num-threads: 2
  outgoing-range: 512
  num-queries-per-thread: 1024
  msg-cache-size: 32m
  rrset-cache-size: 64m
  cache-max-ttl: 86400
  infra-host-ttl: 60
  infra-lame-ttl: 120

  access-control: 127.0.0.0/8 allow
  access-control: 192.168.0.0/24 allow
  access-control: 10.0.0.0/8 allow

  directory: "/etc/unbound"
  use-syslog: yes
  hide-version: yes

  so-rcvbuf: 2m
  so-sndbuf: 2m

  do-ip4: yes
  do-ip6: no
  do-udp: yes
  do-tcp: yes

  local-data: "xxx.dummy.blah A 192.168.0.158"

remote-control:
  control-enable: yes
  control-interface: 127.0.0.1
```
