### ISSUE TITLE
Query for TXT record returns CNAME of the domain

### ISSUE THREAD

**Issue by leonid-shevtsov** [NLnetLabs/unbound#723]
expected result, from Cloudflare:

```
>dig TXT @1.1.1.1 leonid.shevtsov.me

;; ANSWER SECTION:
leonid.shevtsov.me.     900     IN      TXT     "spf snip"
leonid.shevtsov.me.     900     IN      TXT     "google snip"
```

actual result from unbound:

```
>dig TXT @127.0.0.1 leonid.shevtsov.me

;; ANSWER SECTION:
leonid.shevtsov.me.     10      IN      CNAME   cname.vercel-dns.com.
```

The zone uses [Hover](https://www.hover.com) for DNS, so both TXT records and the CNAME are defined there. There is a CNAME for this subdomain because it is hosted on [Vercel](https://vercel.com). This is a typical setup. 

I've never seen it affect TXT record resolution before. Looks like a bug, or at least behavior that doesn't match the norm. For example, Google site verification works, and [mxtoolbox finds the SPF record](https://mxtoolbox.com/SuperTool.aspx?action=spf%3aleonid.shevtsov.me&run=toolpage). But unbound cannot find either TXT record.

**Unbound version**

Unbound 1.16.1 on macOS

no options related to resolution have been changed from their defaults.

**Comment by Philip-NLnetLabs** [comment]
Sorry for the late reply. Is the CNAME gone by now?

**Comment by leonid-shevtsov** [comment]
Sorry it's hard for me to validate right now as i moved the domain to cloudflare DNS and proxy. so the issue would certainly not reproduce.

Also, our product switched away from unbound because of this issue (it affected several customers), we're currently using public DNS again. Would love to see some conclusion.

**Comment by krzsztf1** [comment]
Hi,
I have a similar problem to the one described here. When I query my unbound DNS resolver it gives me the following answer every time

```
root@proxy2:~# dig public2.logintrade.net txt

; <<>> DiG 9.18.28-0ubuntu0.20.04.1-Ubuntu <<>> public2.logintrade.net txt
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29742
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;public2.logintrade.net.                IN      TXT

;; ANSWER SECTION:
public2.logintrade.net. 297     IN      CNAME   cluster.logintrade.net.

;; AUTHORITY SECTION:
logintrade.net.         1797    IN      SOA     maria.ns.cloudflare.com. dns.cloudflare.com. 2363685103 10000 2400 604800 1800

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1) (UDP)
```

instead of the 

```
root@proxy2:~# dig public2.logintrade.net txt @8.8.8.8

; <<>> DiG 9.18.28-0ubuntu0.20.04.1-Ubuntu <<>> public2.logintrade.net txt @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34724
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;public2.logintrade.net.                IN      TXT

;; ANSWER SECTION:
public2.logintrade.net. 300     IN      TXT     "v=spf1 include:amazonses.com ~all"

;; Query time: 8 msec
;; SERVER: 8.8.8.8#53(8.8.8.8) (UDP)
;; WHEN: Fri Jan 31 18:24:35 CET 2025
;; MSG SIZE  rcvd: 97
```

Unfortunately this is serious because it's a mail server and I definitely need to get the correct TXT records with the SPF value for domains.

My configuarion is as follows
```
server:
    # more cache memory, rrset=msg*2
    rrset-cache-size: 100m
    msg-cache-size: 50m

server:
    do-ip6: no
server:
  remote-control:
    control-enable: yes
    control-interface: 127.0.0.1
    control-port: 8953
server:
    prefetch: yes
    serve-expired: no
server:
    # Send minimum amount of information to upstream servers to enhance
    # privacy. Only sends minimum required labels of the QNAME and sets
    # QTYPE to NS when possible.

    # See RFC 7816 "DNS Query Name Minimisation to Improve Privacy" for
    # details.

    qname-minimisation: yes
server:
    # The following line will configure unbound to perform cryptographic
    # DNSSEC validation using the root trust anchor.
    auto-trust-anchor-file: "/var/lib/unbound/root.key"
```

and
```
root@proxy2:~# unbound -V
Version 1.9.4

Configure line: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --disable-rpath --with-pidfile=/run/unbound.pid --with-rootkey-file=/var/lib/unbound/root.key --with-libevent --with-pythonmodule --enable-subnet --enable-dnstap --enable-systemd --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --libdir=/usr/lib
Linked libs: libevent 2.1.11-stable (it uses epoll), OpenSSL 1.1.1f  31 Mar 2020
Linked modules: dns64 python subnetcache respip validator iterator
```

I've tested the same thing on the other server with the same version of Ubuntu (20.04) and the same version of unbound (1.9.4), and supprinsingly the problem doesn't occur there. So is this some sort of misconfiguration? What should I check?
