### ISSUE TITLE
A complete tutorial for installing and running unbound on windows

### ISSUE THREAD

**Issue by Johny17** [NLnetLabs/unbound#735]
I searched a lot but there is nothing! there is no tutorial for windows. I installed it and there was no shortcut on desktop, so i went to it's folder, after searching and changing service.conf which was hard, finally launched the "unbound.exe" but it wasn't working! nothing happened. I installed the service, and tried again, it finally launched but then it wasn't doing anything!

right now i'm using Adguard Home + Proton vpn. I don't know how to use unbound cause there is almost nothing about it for windows. This is my config by the way. 10.2.0.2 is adguard home ip address. I tried 127.0.0.1 but it didn't work either.

**Found the SOLUTION!**

```
    access-control: 192.168.0.0/16 allow
    access-control: 10.2.0.2/16 allow
    interface: 10.2.0.2
    port: 5353
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes 

forward-zone:
    name: "."
    #forward-tls-upstream: yes

    # AdGuard
    forward-addr: 94.140.14.14
    forward-addr: 94.140.15.15

    # Quad9(Standard)
    forward-addr: 9.9.9.9
    forward-addr: 149.112.112.112

    # Cloudflare
    forward-addr: 1.1.1.1
    forward-addr: 1.0.0.1
```
