### ISSUE TITLE
Does ECS (EDNS) works?

### ISSUE THREAD

**Issue by sergeysedoy97** [NLnetLabs/unbound#772]
**Describe the bug**
I tried various combination of [EDNS settings](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#edns-client-subnet-module-options), but can't get `edns0-client-subnet` record from Google.

```
send-client-subnet: ::/0
send-client-subnet: 0.0.0.0/0
client-subnet-always-forward: yes
client-subnet-zone: .
```

**To reproduce**

```
root@xxx:~# dig o-o.myaddr.google.com txt @127.0.0.1

; <<>> DiG 9.18.1-1ubuntu1.2-Ubuntu <<>> o-o.myaddr.google.com txt @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25952
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;o-o.myaddr.google.com.         IN      TXT

;; ANSWER SECTION:
o-o.myaddr.google.com.  10      IN      TXT     "79.137.196.X"

;; Query time: 4 msec
;; SERVER: 127.0.0.1#53(127.0.0.1) (UDP)
;; WHEN: Fri Oct 28 14:35:19 MSK 2022
;; MSG SIZE  rcvd: 77
```

**Expected behavior**
```
root@xxx:~# dig o-o.myaddr.google.com txt @8.8.8.8

; <<>> DiG 9.18.1-1ubuntu1.2-Ubuntu <<>> o-o.myaddr.google.com txt @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2867
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;o-o.myaddr.google.com.         IN      TXT

;; ANSWER SECTION:
o-o.myaddr.google.com.  60      IN      TXT     "173.194.169.108"
o-o.myaddr.google.com.  60      IN      TXT     "edns0-client-subnet 79.137.196.0/24"

;; Query time: 36 msec
;; SERVER: 8.8.8.8#53(8.8.8.8) (UDP)
;; WHEN: Fri Oct 28 14:35:57 MSK 2022
;; MSG SIZE  rcvd: 126
```

**System:**
 - Unbound version: 1.17.0
 - OS: Ubuntu 22.04 LTS
 - `unbound -V` output:
```
Version 1.17.0

Configure line: --enable-cachedb --enable-ipsecmod --enable-ipset --enable-subnet --enable-tfo-client --enable-tfo-server --with-gnu-ld --with-libbsd --with-libevent=/usr --with-libexpat=/usr --with-libhiredis=/usr --with-libmnl=/usr --with-libnghttp2=/usr --with-pthreads --with-ssl=/usr
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 1.1.1n  15 Mar 2022
Linked modules: dns64 cachedb ipsecmod subnetcache ipset respip validator iterator
TCP Fastopen feature available
```

**Additional information**
Server config part:
```
server:
  access-control: ::/0 allow
  access-control: 0.0.0.0/0 allow
  auto-trust-anchor-file: /usr/local/etc/unbound/root.key
  cache-max-ttl: 86400
  cache-min-ttl: 60
  chroot: ""
  deny-any: yes
  do-daemonize: no
  do-not-query-localhost: no
  edns-tcp-keepalive: yes
  fast-server-num: 13
  fast-server-permil: 1000
  hide-http-user-agent: yes
  hide-identity: yes
  hide-trustanchor: yes
  hide-version: yes
  http-query-buffer-size: 1048576
  http-response-buffer-size: 1048576
  incoming-num-tcp: 2
  infra-cache-numhosts: 512
  infra-cache-slabs: 2
  interface: 127.0.0.1@${UNBOUND_PORT}
  ip-ratelimit-factor: 0
  ip-ratelimit-size: 1048576
  ip-ratelimit-slabs: 2
  ip-ratelimit: 0
  key-cache-size: 1048576
  key-cache-slabs: 2
  log-time-ascii: no
  max-reuse-tcp-queries: ${MAXCONN}
  module-config: "subnetcache validator iterator"
  module-config: "validator cachedb iterator"
  msg-cache-size: 1048576
  msg-cache-slabs: 2
  neg-cache-size: 1048576
  num-queries-per-thread: ${MAXCONN}
  num-threads: 2
  outgoing-num-tcp: 2
  prefetch-key: yes
  prefetch: yes
  ratelimit-factor: 0
  ratelimit-size: 1048576
  ratelimit-slabs: 2
  ratelimit: 0
  root-hints: /etc/named.cache
  rrset-cache-size: 1048576
  rrset-cache-slabs: 2
  serve-expired: yes
  serve-expired-ttl: 86400
  serve-expired-client-timeout: 1800
  so-reuseport: yes
  statistics-interval: 0
  stream-wait-size: 1048576
  tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt
  use-caps-for-id: yes
  use-syslog: no
  username: ""
  verbosity: 0
```

Thank You!
