### ISSUE TITLE
Unbound mishandles some cases and return malformed dns packet 

### ISSUE THREAD

**Issue by mingkwind** [NLnetLabs/unbound#784]
Hi,

**Describe**
When Unbound receive malformed dns request packets, it returns malformed dns packets to the client without proper verification, which will give the user a distrust or malicious data.  Other authoritative dns servers return the correctly formatted dns packet.

**To reproduce**
1. start unbound. The `unbound.conf` configuration options are as follows
    ```
   server:
        verbosity: 1
        num-threads: 2
        interface: 0.0.0.0
        interface: ::0
        port: 5357
        do-not-query-localhost: no
        access-control: 127.0.0.1/8 allow
        access-control: ::0/0 allow
        username: "root"

    forward-zone:
        name: '.'
        forward-addr: 127.0.0.1
    ```
2. use python3 script to send the bad dns request packet to unbound, the specific construction method of the dns request packet is as follows: 
    set the the fifth 4-bytes  to 0x00e3(or other numbers except 0x0000),  which represents the number of Authority RRs is 0x00e3, and set the authoritative nameservers section to empty.
   you can do the above by these two files:
   https://643684107.oss-cn-beijing.aliyuncs.com/unbound/dns_request.py
   https://643684107.oss-cn-beijing.aliyuncs.com/unbound/request
   then run the python script:
   ```bash
    python3 dns_request.py request 5357
   ```
3. receive the response packet from unbound

**Expected behavior**
  After running the python script, the output is as follows:
   ```
      Sending DNS query to 127.0.0.1:5357
      DNS query data:
      0000  31 32 01 00 00 01 00 00 00 E3 00 00 06 63 65 72    12...........cer
      0010  74 30 31 07 65 78 61 6D 70 6C 65 00 00 25 00 01    t01.example..%..
      Received DNS response from 127.0.0.1:5357
      DNS response data:
      0000  31 32 81 01 00 01 00 00 00 E3 00 00 06 63 65 72    12...........cer
      0010  74 30 31 07 65 78 61 6D 70 6C 65 00 00 25 00 01    t01.example..%..
  ```
  We can find that unbound think the dns request paket we send are DNS Query Format Error and it set the RCODE to 1(the 4th  byte: 0x01) in the dns response packet, but the fifth 4-bytes(Authority RRs)  of the packet is stiil  0x00e3 instead of 0x0000 and  the authoritative nameservers section of  the packet is empty, so the dns response packet is malformed. 

  In contrast, Bind(a DNS resolver like Unbound) resturns the correctly formatted dns packet: 
  ```
      Sending DNS query to 127.0.0.1:7777
      DNS query data:
      0000  31 32 01 00 00 01 00 00 00 E3 00 00 06 63 65 72    12...........cer
      0010  74 30 31 07 65 78 61 6D 70 6C 65 00 00 25 00 01    t01.example..%..
      Received DNS response from 127.0.0.1:7777
      DNS response data:
      0000  31 32 81 01 00 01 00 00 00 00 00 00 06 63 65 72    12...........cer
      0010  74 30 31 07 65 78 61 6D 70 6C 65 00 00 25 00 01    t01.example..%..
  ```
  
**System:**
 - Unbound version: 1.17.0
 - OS: 20.04.3
 - `unbound -V` output:
     Version 1.17.0

    Configure line:
    Linked libs: mini-event internal (it uses select), OpenSSL 1.1.1f  31 Mar 2020
    Linked modules: dns64 respip validator iterator
    
    BSD licensed, see LICENSE in source package for details.
    Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
