### ISSUE TITLE
[FR] Parallelize upstream servers requests

### ISSUE THREAD

**Issue by wsw70** [NLnetLabs/unbound#785]
**Current behavior**

With the setting

```
forward-zone:
    name: "."
    forward-addr: 1.1.1.1
    forward-addr: 8.8.8.8
    forward-addr: 8.8.4.4
```

each of the upstream servers is queried sequentially (a chain of fallbacks of sorts)

**Describe the desired feature**

Adding a boolean setting `forward-addr-all` (or something like that) would allow to make all the queries at the same time, and use the one that replies first.

**Potential use-case**

This behavior would speed up the DNS resolution by always using the fastest DNS server (which may be different at different times, for the same set of DNS servers)
