### ISSUE TITLE
Unbound cannot handle reverse DNS lookups for private IPs

### ISSUE THREAD

**Issue by mingkwind** [NLnetLabs/unbound#788]
**Describe the bug**
Unbound cannot handle reverse DNS lookups for private IPs.

**To reproduce**
1. Start unbound. The unbound.conf configuration options are as follows.
```
server:
    verbosity: 1
    num-threads: 2
    interface: 0.0.0.0
    interface: ::0
    port: 53
    do-not-query-localhost: no
    access-control: 127.0.0.1/8 allow
    access-control: ::0/0 allow
    username: "root"

forward-zone:
    name: '.'
    forward-addr: 127.0.0.1
```
2. Use dig to do a reverse DNS lookups for one private IP.
Just like this:
```bash
 dig -x 172.16.1.1  @127.0.0.1 -p 53
```

**Expected behavior**
The result of the dig show this:
```
; <<>> DiG 9.16.1-Ubuntu <<>> -x 172.16.1.1 @127.0.0.1 -p 53
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 33507
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;1.1.16.172.in-addr.arpa.	IN	PTR

;; AUTHORITY SECTION:
16.172.in-addr.arpa.	10800	IN	SOA	localhost. nobody.invalid. 1 3600 1200 604800 10800

;; Query time: 5 msec
;; SERVER: 127.0.0.1#5357(127.0.0.1)
;; WHEN: Sun Nov 20 16:18:15 CST 2022
;; MSG SIZE  rcvd: 111
```
We can find that the status of the header is NXDOMAIN, and  it return the resonse packet directly without iteratively querying the upstream domain name server. While other dns servers like bind \ dnsmasq \ smartdns \ knot do iteratively querying the upstream domain name server for the reverse DNS lookups  and return the packet with the Rcode 0 which means the packet is NOERRAR.

**System:**
- Unbound version: 1.17.0

- OS: Ubuntu 20.04.3

- unbound -V output:
   Version 1.17.0

  Configure line:
  Linked libs: mini-event internal (it uses select), OpenSSL 1.1.1f 31 Mar 2020
  Linked modules: dns64 respip validator iterator
      
  BSD licensed, see LICENSE in source package for details.
  Report bugs to [unbound-bugs@nlnetlabs.nl](mailto:unbound-bugs@nlnetlabs.nl) or https://github.com/NLnetLabs/unbound/issues
