### ISSUE TITLE
DNS Stops resolving after a period of inactivity, also kicks off VPN.

### ISSUE THREAD

**Issue by RexBytes** [NLnetLabs/unbound#845]
Hello,

**Describe the bug:**
Unbound stops resolving DNS
      
I am using unbound on a laptop as a portable DNS resolver.
I am connecting through an openVPN.
After a period of inactivity and leaving laptop alone DNS doesn't resolve and I have to restart the service.
(Unbound failing seems to kick me off the VPN and the VPN disconnects)
      
Inelegant Workaround: 
      
If anyone needs a quick ugly fix I am restarting the unbound service every 30 mins,
this just works... I can come back to laptop hours later and all connections are still up.
      
I don't think the VPN is the problem as it now stays up with this workaround in place.
      
Add this to your root user crontab,

`*/30 * * * * /usr/bin/systemctl restart unbound`

**To reproduce:**

I'm using a fresh install of linux mint.
Connect to a VPN provider using openVPN.
Unbound installed natively, NOT in a docker container.
Start it all up, wait a few hours for it to stop resolving.

```
unbound.conf:

server:
    logfile: "/var/log/unbound/unbound.log"
    verbosity: 1
    interface: 127.0.0.1@5335
    interface: 172.17.0.1@5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    do-ip6: no

    prefer-ip6: no

    root-hints: "/var/lib/unbound/root.hints"

    harden-glue: yes

    harden-dnssec-stripped: yes

    use-caps-for-id: no

    edns-buffer-size: 1232

    prefetch: yes

    num-threads: 1


    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 172.17.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10

    remote-control:
	control-enable: yes
        control-interface: 127.0.0.1
        control-port: 8953

```

**System:**
Unbound Version 1.13.1
OpenVPN Version 2.5.5 
System:  Kernel: 5.15.0-58-generic x86_64 bits: Desktop: Cinnamon 5.6.7, Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
CPU: Intel Core i7-6500U 

**Expected Behaviour:**
      
I'd like to have my DNS requests resolving, VPN connection still up, after 12 hours or more of inactivity.
 Without my workaround.
      
 Thank you.
