### ISSUE TITLE
dump_cache behaves strangely when subnetcache module is enabled.

### ISSUE THREAD

**Issue by YoungjuWang** [NLnetLabs/unbound#855]
**Describe the bug**

I also checked in unbound 1.17.1, but when the subnetcache module is activated, the cache for general A record lookup is not checked in the unbound-control dump_cache command.

The problem does not occur without the subnetcache module. (like Expected behavior)

**To reproduce**
1. enable subnetcache `module-config: "subnetcache iterator"`
2. resolving any A record `# dig @localhost -p 5353 time.google.com +short` 
3. check dump_cache `./unbound-control dump_cache |grep time`

**Expected behavior**

```bash
# ./unbound-control dump_cache |grep time
time.google.com.	14399	IN	A	216.239.35.12
time.google.com.	14399	IN	A	216.239.35.4
time.google.com.	14399	IN	A	216.239.35.8
time.google.com.	14399	IN	A	216.239.35.0
msg time.google.com. IN A 32896 1 14399 2 1 0 0
time.google.com. IN A 0
```

**System:**
 - Unbound version: 1.17.1
 - OS:  rocky9 / ubuntu 18.04
 - `unbound -V` output:
```
Version 1.17.1

Configure line: --enable-subnet
Linked libs: mini-event internal (it uses select), OpenSSL 1.1.1  11 Sep 2018
Linked modules: dns64 subnetcache respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Additional information**
Add any other information that you may have gathered about the issue here.

**Comment by wcawijngaards** [comment]
If I try this, then it works fine. The cachedump shows the looked up domain names. Also with the subnetmodule in the module-config.

What could be happening is that there is configuration, that is not there in the test I did, where subnet is enabled for the particular query. As a result, the reply is stored in the subnetcache. And not in the global rrset and msg cache. The dump_cache command dumps the rrset and msg cache, but not the subnet specific cache contents.

**Comment by YoungjuWang** [comment]
@wcawijngaards Hello, Thank you for quick response.

Below is the content of the config file I used.
```yaml
server:
        verbosity: 5
        send-client-subnet: 0.0.0.0/0
        max-client-subnet-ipv4: 32
        interface: 0.0.0.0
        port: 5353
        access-control: 0.0.0.0/0 allow
        do-not-query-localhost: no
        module-config: "subnetcache iterator"
remote-control:
        control-enable: yes
        control-interface: 127.0.0.1
```

Please check if my understanding is correct.

1.
Even in the case of A record search (time.google.com A), since the ecs value is generated by the 'send-client-subnet' option, is it correct that the response is stored in subnetcache rather than in general rrset-cache or msg-cache?

2.
If the above is correct, how to check the subnetcache item and how to flush the cache? 
(I wonder if it is possible to flush the subnet cache like "unbound-control flush time.google.com" rather than "unbound-control reload".)

Thanks.
