### ISSUE TITLE
error:  unknown keyword 'redis-server-password'

### ISSUE THREAD

**Issue by jagerzhang** [NLnetLabs/unbound#872]
Version 1.17.1
```
root@bde699726bf7:/opt/unbound# unbound -V
Version 1.17.1

Configure line: --disable-dependency-tracking --prefix=/opt/unbound --with-pthreads --with-username=_unbound --with-ssl=/opt/openssl --with-libevent --with-libnghttp2 --enable-dnstap --enable-tfo-server --enable-tfo-client --enable-event-api --enable-subnet
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 3.1.0 14 Mar 2023
Linked modules: dns64 subnetcache respip validator iterator
TCP Fastopen feature available

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

unbound.conf from https://github.com/NLnetLabs/unbound/issues/833
```
server:
  interface: 127.0.0.1
  interface: ::1
  port: 53
  cache-max-ttl: 5184000
  cache-min-ttl: 5184000
  cache-max-negative-ttl: 604800
  val-bogus-ttl: 0
  delay-close: 10000
  chroot: ""
  username: user
  directory: ""
  pidfile: ""
  do-not-query-localhost: no
  module-config: "validator cachedb iterator"

cachedb:
  backend: redis
  redis-server-host: ::1
  redis-server-port: 6379
  redis-server-password: "passwd123"
  # redis-server-path: "/var/lib/redis/redis-server.sock"
  redis-timeout: 5000

forward-zone:
  name: "."
  forward-addr: ::1@10053
```

unbound-checkconf  report errors:
```
root@bde699726bf7:/opt/unbound# unbound-checkconf 
/etc/unbound/custom.conf.d/unbound.conf:21: error: unknown keyword 'redis-server-password'
/etc/unbound/custom.conf.d/unbound.conf:21: error: stray ':'
/etc/unbound/custom.conf.d/unbound.conf:21: error: stray '"'
/etc/unbound/custom.conf.d/unbound.conf:21: error: unknown keyword 'passwd123'
/etc/unbound/custom.conf.d/unbound.conf:21: error: stray '"'
read /opt/unbound/etc/unbound/unbound.conf failed: 5 errors in configuration file
```
