### ISSUE TITLE
access-control-view: netmasks shorter than 8 don't work

### ISSUE THREAD

**Issue by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [NLnetLabs/unbound#922]
Netmasks shorter than 8 bits don't work in directive `access-control-view`.

**To reproduce**
1. Create config
<details>
  <summary>unbound.conf</summary>

```
server:
    use-syslog:                 no

    do-ip6:                     no
    do-udp:                     yes
    do-tcp:                     yes
    verbosity:                  0
    statistics-interval:        0
    module-config:              "respip iterator"
    pidfile:                    /run/unbound.pid
    chroot:                     ""
    hide-identity:              yes
    hide-version:               yes

    num-threads:                2
    interface:                  0.0.0.0
    so-reuseport:               yes
    target-fetch-policy:        "0 0 0 0 0"
    minimal-responses:          yes
    rrset-roundrobin:           yes

    access-control:             127.0.0.0/8     allow_snoop

# works
#    access-control-view:       127.0.0.1       test_view
#    access-control-view:       127.0.0.0/8     test_view
#    access-control-view:       127.0.0.1/8     test_view

# does not work
#    access-control-view:       127.0.0.1/0     test_view
#    access-control-view:       127.0.0.0/7     test_view
#    access-control-view:       126.0.0.0/7     test_view
    access-control-view:        0.0.0.0/0       test_view

# global definition
    local-zone:                 .       typetransparent
    local-data:                 "qqq.   IN      CNAME   ERROR--global-record"


view:
    name:                       test_view

    local-zone:                 .       typetransparent
    local-data:                 "qqq.   IN      CNAME   OK--test-view-record"

#remote-control:
#    control-enable:             yes
#    control-interface:          127.0.0.1
```
</details>

2. Uncomment one of `access-control-view` directives.
3. Send DNS query from the same host:
```
host -t cname qqq. 127.0.0.1
```
or
```
host -t a qqq. 127.0.0.1
```
4. Do the test for `access-control-view` with netmask shorter than 8 and for 8 or longer.
For shorter netmasks you will get:
```
qqq is an alias for ERROR--global-record.
```
for 8 and longer:
```
qqq is an alias for OK--test-view-record.
```

**Expected behavior**
The same answer for all netmasks:
```
qqq is an alias for OK--test-view-record.
```

**System:**
 - Unbound version: 1.17.1
 - OS: Ubuntu 23.04
 - `unbound -V` output:
```
Version 1.17.1

Configure line: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-pythonmodule --with-pyunbound --enable-subnet --enable-dnstap --enable-systemd --with-libnghttp2 --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --disable-rpath --with-pidfile=/run/unbound.pid --with-libevent --enable-tfo-client --with-rootkey-file=/usr/share/dns/root.key --enable-tfo-server
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 3.0.8 7 Feb 2023
Linked modules: dns64 python subnetcache respip validator iterator
TCP Fastopen feature available

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Additional information**
The same problem is in unbound-1.6.7 (Ubuntu 18.04).

**Comment by gthess** [comment]
This is not a problem with netmasks.
Unbound will try to match the most specific ACL for a client. In this case 127.0.0.0/8 is already defined. If there is no configured view for that it will go to global local records or resolution based on the acl type.

Furthermore, 127.0.0.0/8 is special in the way that it is implicitly configured in Unbound with an 'allow' access to allow localhost connections. This means that an ACL for 127.0.0.0/8 always exists by default with no view attached to it. You can overwrite the acl type like in your configuration, but you cannot remove it altogether.

You can check that netmasks shorter than 8 do work by using the following configuration for example:
```
server:
    ...
    interface: 192.168.1.1 # I'll use this address as another address available to the system; you can pick your real one
    ...
    access-control: 192.168.1.1/7 allow_snoop  # You need explicit access-control for anything other than 'allow'

# works :)
    access-control-view: 192.168.1.1/7 test_view  # If an access-control option is not defined above, an implicit one set to 'allow' will be created

# global definition
    local-zone: . typetransparent
    local-data: "qqq.   IN      CNAME   ERROR--global-record"

view:
    name: test_view
    local-zone: . typetransparent
    local-data: "qqq.   IN      CNAME   OK--test-view-record"
```
Closing this as a non-issue but feel free to reopen for further questions/clarifications :)
