### ISSUE TITLE
Receiving Communication Error timed out  Host : Freebsd

### ISSUE THREAD

**Issue by presci** [NLnetLabs/unbound#995]
I am getting communications error timed out on my Freebsd Server
```dig @192.168.1.87 adserver.example.com 
;; communications error to 192.168.1.87#53: timed out
```
but when I use dig @127.0.0.1 adserver.example.com it works and returns the result.
Here is my /etc/resolv.conf
```
root@BoosterGold:/usr/local/etc/unbound # cat /etc/resolv.conf
# Generated by resolvconf
nameserver 192.168.1.1
```
Here is my /etc/hosts
```root@BoosterGold:/usr/local/etc/unbound # cat /etc/hosts
::1			localhost localhost.my.domain
127.0.0.1		localhost localhost.my.domain
192.168.1.87    BoosterGold BoosterGold.mydomain
```
I have given the static ip address to the server on the Router. And have added the Primary DNS as 192.168.1.87 that's my Freebsd Server. Then I have added cloudfare as second and third server in the router.
(I am able to connect to the server via ssh with the ip address as well as the hostname)
Primary intention of the server is the block advertisement and certain sites. Although I am not sure if adding the second and third server on router makes sense was thinking about removing that from the router and adding it to unbound.conf in forward-zone. 

Here is my unbound.conf
```
server:
    interface: 0.0.0.0

    access-control: 192.168.0.0/24 allow
    access-control: 127.0.0.1 allow
    access-control: ::1 allow
    access-control: 0.0.0.0/0 deny
    access-control: ::/0 deny

    
    pidfile: "/var/run/unbound.pid"
    use-syslog: yes
    verbosity: 1 
    log-queries: yes
    log-replies: yes

    local-zone: "adserver.example.com" always_nxdomain
    local-zone: "adserver1.example.com" always_nxdomain
    local-zone: "adserver2.example.com" always_nxdomain

remote-control:
    control-enable: yes
```
Any help would be highly appreciated. Thank you
